## Set Date Range

In [73]:
start_dt = '2025-11-29'
end_dt = '2025-12-05'

## Invited Users - Batch 1+2

In [74]:
# invited = pd.read_csv("dw_invited_users.csv") # This is local csv file
invited_users = 'sparky_panel_updated' # This is how data is saved in hive and BQ

## Load Libraries

In [75]:
import os
import pickle
from datetime import datetime, timedelta
from io import BytesIO
from trino.dbapi import connect
from trino.auth import BasicAuthentication

import pandas as pd
import db_dtypes
import pytz
#from src.config import SETTINGS
from google.auth.exceptions import DefaultCredentialsError
from google.cloud import bigquery#, storage
import warnings

warnings.filterwarnings("ignore")
from dotenv import load_dotenv
load_dotenv()

#pip install pandas-gbq ----------to create a table in BQ

True

## Setting up BQ and Hive connection

In [76]:
host_name = "presto-datadiscovery.walmart.com"
port_number = 8443
user_name = "k0t0e62"
password = os.getenv("DB_PASSWORD")

In [77]:
conn = connect(
    host=host_name,
    port=port_number,
    user=user_name,
    auth=BasicAuthentication(user_name, password),
    catalog="hive",
    http_scheme="https",
    verify='./merged_cacert.pem'
)

cur = conn.cursor()

In [78]:
def get_bigquery_client(project: str) -> bigquery.Client:
    
    if not os.environ["GOOGLE_APPLICATION_CREDENTIALS"]:
        raise DefaultCredentialsError(
            """GOOGLE_APPLICATION_CREDENTIALS environment variable not set. 
                    Please go to .env file and set it to the path of your GCP service account key file."""
        )

    if not project:
        raise EnvironmentError(
            "GCP_PROJECT environment variable not set. Please go to .env file and set it to your GCP project ID."
        )

    return bigquery.Client(project=os.environ["GCP_PROJECT"])


# ----------------------- Load BigQuery Data -----------------------
def load_bq_data(query: str) -> pd.DataFrame:
    """
    Load data from BigQuery.

    Parameters:
    - query: SQL query to execute
    - client: BigQuery client

    Returns:
    - Pandas DataFrame containing the query result
    """

    client = get_bigquery_client(project=os.environ["GCP_PROJECT"])
    return client.query(query).to_dataframe()


# ----------------------- Load BigQuery Data -----------------------
def write_dataframe_to_bigquery(
    dataframe: pd.DataFrame,
    table_name: str,
    schema=None,
    drop_table=True,
) -> None:
    """
    Write a pandas DataFrame to a BigQuery table.
    ! by default, it drops wmt-transplan-ib-forecasting.transplan_ob_forecasting.{table_name} table
    ! please refactor in the future release to make it more generic

    Parameters:
    - dataframe: Pandas DataFrame to write to BigQuery
    - table_name: Name of the BigQuery table to write to
    - schema: Schema of data structure
    - bq_client: BigQuery client object

    Returns:
    - BigQuery job result
    """
    bq_client = get_bigquery_client(project=os.environ["GCP_PROJECT"])

    if drop_table:
        bq_client.query(
            f"DROP TABLE IF EXISTS wmt-transplan-ib-forecasting.transplan_ib_forecasting.{table_name}"
        )
    target_dataset = bq_client.dataset("transplan_ib_forecasting")
    target_table = target_dataset.table(table_name)
    job = bq_client.load_table_from_dataframe(
        dataframe,
        target_table,
        job_config=schema,
    )
    return job.result()

# Customer Usage Metric 0 - Total classic app sessions

In [ ]:
print("Total classic app sessions")

sql = f"""
WITH invited_users AS (
    SELECT DISTINCT pg_cust_acct_id AS pg_cust_id
    FROM gpadata_analytics.{invited_users}
),

login_users_sessn AS (
    SELECT DISTINCT a.pg_cust_id
    FROM (
        SELECT DISTINCT pg_cust_id, visitor_cooke_val, brwsr_sessn_cooke_val
        FROM ww_csd_dl_tables.csd_site_traffic_rptr_event_log_vw
        WHERE event_dt BETWEEN DATE '{start_dt}' AND DATE '{end_dt}'
            AND (assoc_ind = 'false' OR assoc_ind IS NULL) -- Exclude the associates
            AND json_extract_scalar(page_attr, '$.nm') = 'homePage' -- Users that reached home page
            AND actn_catg_nm = 'pageView'
    ) a
    JOIN invited_users i ON i.pg_cust_id = a.pg_cust_id
)

SELECT 
    COUNT(DISTINCT a.pg_cust_id) AS classic_users, 
    COUNT(DISTINCT a.brwsr_sessn_cooke_val) AS classic_sessn
FROM ww_csd_dl_tables.csd_site_traffic_event_log_vw a
JOIN login_users_sessn i ON i.pg_cust_id = a.pg_cust_id -- Only keep the loggin users
WHERE event_dt BETWEEN DATE '{start_dt}' AND DATE '{end_dt}'
    AND (assoc_ind = 'false' OR assoc_ind IS NULL) -- Exclude the associates
    AND tenant_ste_cd IN ('US_GLASS_ANDROID', 'US_GLASS_IOS')
    AND actn_catg_nm = 'pageView'
    AND bot_ind = 0
"""

cur.execute(sql)
rows = cur.fetchall()
cols = [desc[0] for desc in cur.description]   # extract column names
glass_app_session = pd.DataFrame(rows, columns=cols)
glass_app_session.head()

Total classic app sessions

## Customer Usage Engagement Funnel Metric 1 - Logged In Users/ Sessions

In [ ]:
print("Logged in users/ sessions")

sql = f"""
WITH invited_users AS (
SELECT DISTINCT pg_cust_acct_id AS pg_cust_id
FROM gpadata_analytics.{invited_users})

SELECT COUNT(DISTINCT a.pg_cust_id) AS login_users,
       COUNT(DISTINCT a.brwsr_sessn_cooke_val) AS login_sessn
FROM (SELECT DISTINCT pg_cust_id, visitor_cooke_val, brwsr_sessn_cooke_val
FROM ww_csd_dl_tables.csd_site_traffic_rptr_event_log_vw
WHERE event_dt BETWEEN DATE '{start_dt}' AND DATE '{end_dt}'
AND (assoc_ind = 'false' OR assoc_ind is null) -- Exclude the associates
AND json_extract_scalar(page_attr, '$.nm') = 'homePage' -- Users that reached home page
AND actn_catg_nm = 'pageView') a
JOIN invited_users i
ON i.pg_cust_id = a.pg_cust_id -- To only keep the invited users
"""

cur.execute(sql)
rows = cur.fetchall()
cols = [desc[0] for desc in cur.description]   # extract column names
login_users = pd.DataFrame(rows, columns=cols)
login_users.head()

Logged in users/ sessions

   login_users  login_sessn
0         3948         9029

## Customer Usage Engagement Funnel Metric 2 - Interacted Users and sessions

In [ ]:
print("Interacted Users/Sessions")

sql = f"""
WITH invited_users AS (
SELECT DISTINCT pg_cust_acct_id AS pg_cust_id
FROM gpadata_analytics.{invited_users})

SELECT
  COUNT(DISTINCT a.pg_cust_id) AS interacted_users,
  COUNT(DISTINCT brwsr_sessn_cooke_val) AS interacted_sessn
FROM (SELECT DISTINCT pg_cust_id, brwsr_sessn_cooke_val FROM ww_csd_dl_tables.csd_site_traffic_rptr_event_log_vw
WHERE event_dt BETWEEN DATE '{start_dt}' AND DATE '{end_dt}'
AND (assoc_ind = 'false' OR assoc_ind is null) -- Exclude the associates
AND actn_catg_nm IN ('onClick') 
AND pg_cust_id IS NOT NULL) a -- This will exclude the onboarding events
JOIN invited_users i
ON i.pg_cust_id = a.pg_cust_id -- To only keep the invited users
"""

cur.execute(sql)
rows = cur.fetchall()
cols = [desc[0] for desc in cur.description]   # extract column names
interacted_users = pd.DataFrame(rows, columns=cols)
interacted_users.head()

Interacted Users/Sessions

   interacted_users  interacted_sessn
0              3728              8198

## Metric 3- Users with at least 1 bounce session/ Bounce Sessions

In [ ]:
print("Bounced Users/ Sessions")

sql = f"""
WITH invited_users AS (
SELECT DISTINCT pg_cust_acct_id AS pg_cust_id
FROM gpadata_analytics.{invited_users}),

bounce_sessions AS (
SELECT
  pg_cust_id,
  brwsr_sessn_cooke_val
FROM ww_csd_dl_tables.csd_site_traffic_rptr_event_log_vw
WHERE event_dt BETWEEN DATE '{start_dt}' AND DATE '{end_dt}'
  AND (assoc_ind = 'false' OR assoc_ind IS NULL)
  AND actn_catg_nm IN ('onClick','pageView')
  AND pg_cust_id IS NOT NULL
GROUP BY pg_cust_id, brwsr_sessn_cooke_val
HAVING
  -- no clicks in the session
  SUM(CASE WHEN actn_catg_nm = 'onClick' THEN 1 ELSE 0 END) = 0
  -- at least one homepage pageView
  AND SUM(CASE WHEN actn_catg_nm = 'pageView' AND cntxt_nm = 'homePage' THEN 1 ELSE 0 END) >= 1
  -- no pageViews that are NOT homepage
  AND SUM(CASE WHEN actn_catg_nm = 'pageView' AND cntxt_nm <> 'homePage' THEN 1 ELSE 0 END) = 0)


SELECT COUNT(DISTINCT a.pg_cust_id) bounce_cust_ct,
       COUNT(DISTINCT a.brwsr_sessn_cooke_val) bounce_sessn_ct
FROM bounce_sessions a
JOIN invited_users i
ON i.pg_cust_id = a.pg_cust_id -- To only keep the invited users
"""

cur.execute(sql)
rows = cur.fetchall()
cols = [desc[0] for desc in cur.description]   # extract column names
bounce_users = pd.DataFrame(rows, columns=cols)
bounce_users.head()

Bounced Users/ Sessions

   bounce_cust_ct  bounce_sessn_ct
0              20               21

## Customer usage Engagement Funnel Metric 
 1. Meaningfully Interacted Users, Session, Count
 2. Users, Sessions, Count with message
 3. Users, Sessions, Count of Click category tile
 4. Users, Sessions, Count of Click Home Page tile
 5. Users, Sessions, Count of Click Recent tile

In [ ]:
print("Meaningfully Interacted Users")

sql = f"""
WITH invited_users AS (
SELECT DISTINCT pg_cust_acct_id AS pg_cust_id
FROM gpadata_analytics.{invited_users}),

meaningful_interactions AS (SELECT
  pg_cust_id,
  MAX(CASE WHEN (json_extract_scalar(payload_txt, '$.eventType') = 'SPARKY_CHAT_SEND') THEN 1 ELSE 0 END) AS sent_msg,
  MAX(CASE WHEN (cntxt_nm = 'recentPage' AND json_extract_scalar(payload_txt, '$.moduleName') IN ('OrderCard', 'ChatCard', 'ShopCard')) THEN 1 ELSE 0 END) AS c_recent_card,
  MAX(CASE WHEN (cntxt_nm = 'homePage' AND json_extract_scalar(payload_txt, '$.moduleName') IN ('SHOP', 'WELCOME', 'PRODUCT')) THEN 1 ELSE 0 END) AS c_home_card,
  MAX(CASE WHEN (cntxt_nm = 'categoryPage' AND json_extract_scalar(payload_txt, '$.moduleType') = 'categoryCard') THEN 1 ELSE 0 END) AS c_category_card
FROM ww_csd_dl_tables.csd_site_traffic_rptr_event_log_vw
WHERE event_dt BETWEEN DATE '{start_dt}' AND DATE '{end_dt}'
AND (assoc_ind = 'false' OR assoc_ind is null) -- Exclude the associates
AND ((json_extract_scalar(payload_txt, '$.eventType') = 'SPARKY_CHAT_SEND') -- Sent a message on Sparky
    OR (cntxt_nm = 'recentPage' 
          AND actn_catg_nm = 'onClick' 
          AND json_extract_scalar(payload_txt, '$.actionSubCateg') = 'cardClick' 
          AND json_extract_scalar(payload_txt, '$.moduleName') IN ('OrderCard', 'ChatCard', 'ShopCard')
      ) -- Clicked on Recent cards
    OR (cntxt_nm = 'homePage' 
          AND actn_catg_nm = 'onClick' 
          AND json_extract_scalar(payload_txt, '$.actionSubCateg') = 'cardClick' 
          AND json_extract_scalar(payload_txt, '$.moduleName') IN ('SHOP', 'WELCOME', 'PRODUCT')
      ) -- Clicked on Home Page Cards
    OR (cntxt_nm = 'categoryPage'
          AND actn_catg_nm = 'onClick' 
          AND json_extract_scalar(payload_txt, '$.actionSubCateg') = 'cardClick' 
          AND json_extract_scalar(payload_txt, '$.moduleType') = 'categoryCard'
      ) --  Clicked on Category Cards
    )
GROUP BY 1
)


SELECT COUNT(DISTINCT a.pg_cust_id) AS users_meaningful_interaction,
       COUNT(DISTINCT CASE WHEN sent_msg = 1 THEN a.pg_cust_id END) AS users_sent_msg,
       COUNT(DISTINCT CASE WHEN c_category_card = 1 THEN a.pg_cust_id END) AS users_click_category_card,
       COUNT(DISTINCT CASE WHEN c_home_card = 1 THEN a.pg_cust_id END) AS users_click_home_card,
       COUNT(DISTINCT CASE WHEN c_recent_card = 1 THEN a.pg_cust_id END) AS users_click_recent_card
FROM meaningful_interactions a
JOIN invited_users i
ON i.pg_cust_id = a.pg_cust_id -- To only keep the invited users

"""

cur.execute(sql)
rows = cur.fetchall()
cols = [desc[0] for desc in cur.description]   # extract column names
meaningful_interacted_users = pd.DataFrame(rows, columns=cols)
meaningful_interacted_users.head()

Meaningfully Interacted Users

,users_meaningful_interaction,users_sent_msg,users_click_category_card,users_click_home_card,users_click_recent_card
0,3187,2639,1002,768,763

In [ ]:
print("Meaningfully Interacted Sessions")

sql = f"""
WITH invited_users AS (
SELECT DISTINCT pg_cust_acct_id AS pg_cust_id
FROM gpadata_analytics.{invited_users}),

meaningful_interactions AS (SELECT a.pg_cust_id,
  brwsr_sessn_cooke_val,
  MAX(CASE WHEN (json_extract_scalar(payload_txt, '$.eventType') = 'SPARKY_CHAT_SEND') THEN 1 ELSE 0 END) AS sent_msg,
  MAX(CASE WHEN (cntxt_nm = 'recentPage' AND json_extract_scalar(payload_txt, '$.moduleName') IN ('OrderCard', 'ChatCard', 'ShopCard')) THEN 1 ELSE 0 END) AS c_recent_card,
  MAX(CASE WHEN (cntxt_nm = 'homePage' AND json_extract_scalar(payload_txt, '$.moduleName') IN ('SHOP', 'WELCOME', 'PRODUCT')) THEN 1 ELSE 0 END) AS c_home_card,
  MAX(CASE WHEN (cntxt_nm = 'categoryPage' AND json_extract_scalar(payload_txt, '$.moduleType') = 'categoryCard') THEN 1 ELSE 0 END) AS c_category_card
FROM ww_csd_dl_tables.csd_site_traffic_rptr_event_log_vw a 
JOIN invited_users i
ON i.pg_cust_id = a.pg_cust_id -- To only keep the invited users
WHERE event_dt BETWEEN DATE '{start_dt}' AND DATE '{end_dt}'
AND (assoc_ind = 'false' OR assoc_ind is null) -- Exclude the associates
AND ((json_extract_scalar(payload_txt, '$.eventType') = 'SPARKY_CHAT_SEND') -- Sent a message on Sparky
    OR (cntxt_nm = 'recentPage' 
          AND actn_catg_nm = 'onClick' 
          AND json_extract_scalar(payload_txt, '$.actionSubCateg') = 'cardClick' 
          AND json_extract_scalar(payload_txt, '$.moduleName') IN ('OrderCard', 'ChatCard', 'ShopCard')
      ) -- Clicked on Recent cards
    OR (cntxt_nm = 'homePage' 
          AND actn_catg_nm = 'onClick' 
          AND json_extract_scalar(payload_txt, '$.actionSubCateg') = 'cardClick' 
          AND json_extract_scalar(payload_txt, '$.moduleName') IN ('SHOP', 'WELCOME', 'PRODUCT')
      ) -- Clicked on Home Page Cards
    OR (cntxt_nm = 'categoryPage'
          AND actn_catg_nm = 'onClick' 
          AND json_extract_scalar(payload_txt, '$.actionSubCateg') = 'cardClick' 
          AND json_extract_scalar(payload_txt, '$.moduleType') = 'categoryCard'
      ) --  Clicked on Category Cards
    )
GROUP BY 1,2
)


SELECT 
      COUNT(DISTINCT brwsr_sessn_cooke_val) AS sessn_meaningful_interaction,
      COUNT(DISTINCT CASE WHEN sent_msg = 1 THEN brwsr_sessn_cooke_val END) AS sessn_sent_msg,
      COUNT(DISTINCT CASE WHEN c_category_card = 1 THEN brwsr_sessn_cooke_val END) AS sessn_click_category_card,
      COUNT(DISTINCT CASE WHEN c_home_card = 1 THEN brwsr_sessn_cooke_val END) AS sessn_click_home_card,
      COUNT(DISTINCT CASE WHEN c_recent_card = 1 THEN brwsr_sessn_cooke_val END) AS sessn_click_recent_card
FROM meaningful_interactions
"""

cur.execute(sql)
rows = cur.fetchall()
cols = [desc[0] for desc in cur.description]   # extract column names
meaningful_interacted_sessn = pd.DataFrame(rows, columns=cols)
meaningful_interacted_sessn.head()

Meaningfully Interacted Sessions

,sessn_meaningful_interaction,sessn_sent_msg,sessn_click_category_card,sessn_click_home_card,sessn_click_recent_card
0,6458,4769,1297,925,1247

In [ ]:
print("Event Counts for Each Interaction Type")

sql = f"""
WITH invited_users AS (
    SELECT DISTINCT pg_cust_acct_id AS pg_cust_id
    FROM gpadata_analytics.{invited_users}
)
SELECT

    -- ALL meaningful interaction events (union of all above, counted at the event/log level, not user)
    (SELECT COUNT(*)
        FROM ww_csd_dl_tables.csd_site_traffic_rptr_event_log_vw e
        JOIN invited_users iu ON iu.pg_cust_id = e.pg_cust_id
        WHERE e.event_dt BETWEEN DATE '{start_dt}' AND DATE '{end_dt}'
          AND (e.assoc_ind = 'false' OR e.assoc_ind IS NULL)
          AND (
                json_extract_scalar(e.payload_txt, '$.eventType') = 'SPARKY_CHAT_SEND'
                OR (
                    e.cntxt_nm = 'recentPage'
                    AND e.actn_catg_nm = 'onClick'
                    AND json_extract_scalar(e.payload_txt, '$.actionSubCateg') = 'cardClick'
                    AND json_extract_scalar(e.payload_txt, '$.moduleName') IN ('OrderCard', 'ChatCard', 'ShopCard')
                )
                OR (
                    e.cntxt_nm = 'homePage'
                    AND e.actn_catg_nm = 'onClick'
                    AND json_extract_scalar(e.payload_txt, '$.actionSubCateg') = 'cardClick'
                    AND json_extract_scalar(e.payload_txt, '$.moduleName') IN ('SHOP', 'WELCOME', 'PRODUCT')
                )
                OR (
                    e.cntxt_nm = 'categoryPage'
                    AND e.actn_catg_nm = 'onClick'
                    AND json_extract_scalar(e.payload_txt, '$.actionSubCateg') = 'cardClick'
                    AND json_extract_scalar(e.payload_txt, '$.moduleType') = 'categoryCard'
                )
          )
    ) AS count_meaningful_interaction,

    -- Sent message count
    (SELECT COUNT(*)
        FROM ww_csd_dl_tables.csd_site_traffic_rptr_event_log_vw e
        JOIN invited_users iu ON iu.pg_cust_id = e.pg_cust_id
        WHERE e.event_dt BETWEEN DATE '{start_dt}' AND DATE '{end_dt}'
          AND (e.assoc_ind = 'false' OR e.assoc_ind IS NULL)
          AND json_extract_scalar(e.payload_txt, '$.eventType') = 'SPARKY_CHAT_SEND'
    ) AS count_sent_msg,

     -- Clicked category card count
    (SELECT COUNT(*)
        FROM ww_csd_dl_tables.csd_site_traffic_rptr_event_log_vw e
        JOIN invited_users iu ON iu.pg_cust_id = e.pg_cust_id
        WHERE e.event_dt BETWEEN DATE '{start_dt}' AND DATE '{end_dt}'
          AND (e.assoc_ind = 'false' OR e.assoc_ind IS NULL)
          AND e.cntxt_nm = 'categoryPage'
          AND e.actn_catg_nm = 'onClick'
          AND json_extract_scalar(e.payload_txt, '$.actionSubCateg') = 'cardClick'
          AND json_extract_scalar(e.payload_txt, '$.moduleType') = 'categoryCard'
    ) AS count_category_card,

    -- Clicked home card count
    (SELECT COUNT(*)
        FROM ww_csd_dl_tables.csd_site_traffic_rptr_event_log_vw e
        JOIN invited_users iu ON iu.pg_cust_id = e.pg_cust_id
        WHERE e.event_dt BETWEEN DATE '{start_dt}' AND DATE '{end_dt}'
          AND (e.assoc_ind = 'false' OR e.assoc_ind IS NULL)
          AND e.cntxt_nm = 'homePage'
          AND e.actn_catg_nm = 'onClick'
          AND json_extract_scalar(e.payload_txt, '$.actionSubCateg') = 'cardClick'
          AND json_extract_scalar(e.payload_txt, '$.moduleName') IN ('SHOP', 'WELCOME', 'PRODUCT')
    ) AS count_home_card,

    -- Clicked recent card count
    (SELECT COUNT(*)
        FROM ww_csd_dl_tables.csd_site_traffic_rptr_event_log_vw e
        JOIN invited_users iu ON iu.pg_cust_id = e.pg_cust_id
        WHERE e.event_dt BETWEEN DATE '{start_dt}' AND DATE '{end_dt}'
          AND (e.assoc_ind = 'false' OR e.assoc_ind IS NULL)
          AND e.cntxt_nm = 'recentPage'
          AND e.actn_catg_nm = 'onClick'
          AND json_extract_scalar(e.payload_txt, '$.actionSubCateg') = 'cardClick'
          AND json_extract_scalar(e.payload_txt, '$.moduleName') IN ('OrderCard', 'ChatCard', 'ShopCard')
    ) AS count_recent_card

"""

cur.execute(sql)
rows = cur.fetchall()
cols = [desc[0] for desc in cur.description]
meaningful_interected_event_counts = pd.DataFrame(rows, columns=cols)
meaningful_interected_event_counts.head()

Event Counts for Each Interaction Type

,count_meaningful_interaction,count_sent_msg,count_category_card,count_home_card,count_recent_card
0,16058,10989,1785,1238,2046

## Customer usage Engagement Funnel Metric 
 1. Users, Session, Count who open shop
 2. Users, Sessions, Count who open category shop
 3. Users, Sessions, Count who open weekly shop
 4. Users, Sessions, Count who open browse shop
 5. Users, Sessions, Count who open Planning (events) shop

In [ ]:
print("Users that opened a shop")

sql = f"""
WITH invited_users AS (
SELECT DISTINCT pg_cust_acct_id AS pg_cust_id
FROM gpadata_analytics.{invited_users})

SELECT
  COUNT(DISTINCT a.pg_cust_id) AS cust_opened_shop,
  COUNT(DISTINCT CASE WHEN cntxt_nm = 'browseShop' THEN a.pg_cust_id END) AS cust_opened_browse_shop,
  COUNT(DISTINCT CASE WHEN cntxt_nm = 'eventShop' THEN a.pg_cust_id END) AS cust_opened_event_shop,
  COUNT(DISTINCT CASE WHEN cntxt_nm = 'weeklyShop' THEN a.pg_cust_id END) AS cust_opened_weekly_shop,
  COUNT(DISTINCT CASE WHEN cntxt_nm = 'categoryShop' THEN a.pg_cust_id END) AS cust_opened_category_shop
FROM (SELECT DISTINCT pg_cust_id, cntxt_nm FROM ww_csd_dl_tables.csd_site_traffic_rptr_event_log_vw
WHERE event_dt BETWEEN DATE '{start_dt}' AND DATE '{end_dt}'
AND (assoc_ind = 'false' OR assoc_ind is null) -- Exclude the associates
AND actn_catg_nm = 'pageView'
AND cntxt_nm in ('eventShop', 'weeklyShop', 'browseShop', 'categoryShop')) a
JOIN invited_users i
ON i.pg_cust_id = a.pg_cust_id -- To only keep the invited users
"""

cur.execute(sql)
rows = cur.fetchall()
cols = [desc[0] for desc in cur.description]   # extract column names
opened_shop_cust = pd.DataFrame(rows, columns=cols)
opened_shop_cust.head()

Users that opened a shop

,cust_opened_shop,cust_opened_browse_shop,cust_opened_event_shop,cust_opened_weekly_shop,cust_opened_category_shop
0,1355,63,116,337,1099

In [ ]:
print("Sessions in which a shop was open")

sql = f"""
WITH invited_users AS (
SELECT DISTINCT pg_cust_acct_id AS pg_cust_id
FROM gpadata_analytics.{invited_users})

SELECT
  COUNT(DISTINCT a.brwsr_sessn_cooke_val) AS sessn_opened_shop,
  COUNT(DISTINCT CASE WHEN cntxt_nm = 'browseShop' THEN a.brwsr_sessn_cooke_val END) AS sessn_opened_browse_shop,
  COUNT(DISTINCT CASE WHEN cntxt_nm = 'eventShop' THEN a.brwsr_sessn_cooke_val END) AS sessn_opened_event_shop,
  COUNT(DISTINCT CASE WHEN cntxt_nm = 'weeklyShop' THEN a.brwsr_sessn_cooke_val END) AS sessn_opened_weekly_shop,
  COUNT(DISTINCT CASE WHEN cntxt_nm = 'categoryShop' THEN a.brwsr_sessn_cooke_val END) AS sessn_opened_category_shop
FROM ww_csd_dl_tables.csd_site_traffic_rptr_event_log_vw a 
JOIN invited_users i
ON i.pg_cust_id = a.pg_cust_id -- To only keep the invited users
WHERE event_dt BETWEEN DATE '{start_dt}' AND DATE '{end_dt}'
AND (assoc_ind = 'false' OR assoc_ind is null) -- Exclude the associates
AND actn_catg_nm = 'pageView'
AND cntxt_nm in ('eventShop', 'weeklyShop', 'browseShop', 'categoryShop')
"""

cur.execute(sql)
rows = cur.fetchall()
cols = [desc[0] for desc in cur.description]   # extract column names
opened_shop_sessn = pd.DataFrame(rows, columns=cols)
opened_shop_sessn.head()

Sessions in which a shop was open

,sessn_opened_shop,sessn_opened_browse_shop,sessn_opened_event_shop,sessn_opened_weekly_shop,sessn_opened_category_shop
0,1817,69,125,390,1427

In [ ]:
print("Count/Number of times a Shop Opened")

sql = f"""
WITH invited_users AS (
    SELECT DISTINCT pg_cust_acct_id AS pg_cust_id
    FROM gpadata_analytics.{invited_users}
),

impressions AS (
    SELECT *,
        json_extract_scalar(payload_txt, '$.pageViewId') AS pageViewId,
        json_extract_scalar(page_attr, '$.nm') AS page_nm
    FROM ww_csd_dl_tables.csd_site_traffic_rptr_event_log_vw e
    JOIN invited_users iu ON iu.pg_cust_id = e.pg_cust_id
    WHERE e.event_dt BETWEEN DATE '{start_dt}' AND DATE '{end_dt}'
      AND (e.assoc_ind = 'false' OR e.assoc_ind IS NULL)
      AND e.actn_catg_nm = 'pageView'
      ---AND e.cntxt_nm IN ('eventShop', 'weeklyShop', 'browseShop', 'categoryShop', 'cart', 'orderDetails', 'discoverMore')
)

SELECT
    COUNT(DISTINCT CASE 
        WHEN cntxt_nm IN ('eventShop', 'weeklyShop', 'browseShop', 'categoryShop')
        THEN pageViewId END) AS count_opened_shop,
    
    COUNT(DISTINCT CASE 
        WHEN cntxt_nm = 'browseShop' AND page_nm = 'browseShop'
        THEN pageViewId END) AS count_opened_browse_shop,
        
    COUNT(DISTINCT CASE 
        WHEN cntxt_nm = 'eventShop' AND page_nm = 'eventShop'
        THEN pageViewId END) AS count_opened_event_shop,

    COUNT(DISTINCT CASE 
        WHEN cntxt_nm = 'weeklyShop' AND page_nm = 'weeklyShop'
        THEN pageViewId END) AS count_opened_weekly_shop,

    COUNT(DISTINCT CASE 
        WHEN cntxt_nm = 'categoryShop' AND page_nm = 'categoryShop'
        THEN pageViewId END) AS count_opened_category_shop

FROM impressions
"""

cur.execute(sql)
rows = cur.fetchall()
cols = [desc[0] for desc in cur.description]
count_opened_shop = pd.DataFrame(rows, columns=cols)
count_opened_shop.head()

Count/Number of times a Shop Opened

,count_opened_shop,count_opened_browse_shop,count_opened_event_shop,count_opened_weekly_shop,count_opened_category_shop
0,4612,164,234,898,3316

## Customer usage Engagement Funnel Metric 
 1. Users, Count that created shop
 2. Users, Count that created browse shop
 3. Users, Count that created Planning (events) shop

In [ ]:
print("Users that created a shop")

sql = f"""
WITH invited_users AS (
    SELECT DISTINCT pg_cust_acct_id AS pg_cust_id
    FROM gpadata_analytics.{invited_users}
)
SELECT
    COUNT(DISTINCT e.pg_cust_id) AS created_shop_users,
    COUNT(DISTINCT e.brwsr_sessn_cooke_val) AS created_shop_sessn,
    COUNT(*) AS count_created_shop
FROM ww_csd_dl_tables.csd_site_traffic_rptr_event_log_vw e
JOIN invited_users iu ON iu.pg_cust_id = e.pg_cust_id
WHERE e.event_dt BETWEEN DATE '{start_dt}' AND DATE '{end_dt}'
  AND (e.assoc_ind = 'false' OR e.assoc_ind IS NULL)
  AND JSON_EXTRACT_SCALAR(e.payload_txt, '$.eventType') = 'SPARKY_CHAT_RECEIVE'
  AND JSON_EXTRACT_SCALAR(e.payload_txt, '$.responseType') = 'SHOP_MESSAGE'
  AND json_extract_scalar(e.payload_txt, '$.shopType') is not null
"""

cur.execute(sql)
rows = cur.fetchall()
cols = [desc[0] for desc in cur.description]
created_shop = pd.DataFrame(rows, columns=cols)
created_shop.head()

Users that created a shop

   created_shop_users  created_shop_sessn  count_created_shop
0                 153                 164                 206

In [ ]:
print("Users that created a shop")

sql = f"""
WITH invited_users AS (
    SELECT DISTINCT pg_cust_acct_id AS pg_cust_id
    FROM gpadata_analytics.{invited_users}
)
SELECT
    COUNT(DISTINCT CASE WHEN json_extract_scalar(payload_txt, '$.shopType') = 'BROWSE' THEN e.pg_cust_id END) AS users_created_browse_shop,
    COUNT(DISTINCT CASE WHEN json_extract_scalar(payload_txt, '$.shopType') = 'EVENT' THEN e.pg_cust_id END) AS users_created_event_shop,
    COUNT(DISTINCT CASE WHEN json_extract_scalar(payload_txt, '$.shopType') = 'BROWSE' THEN brwsr_sessn_cooke_val END) AS sessn_created_browse_shop,
    COUNT(DISTINCT CASE WHEN json_extract_scalar(payload_txt, '$.shopType') = 'EVENT' THEN brwsr_sessn_cooke_val END) AS sessn_created_event_shop,
    COUNT(CASE WHEN json_extract_scalar(payload_txt, '$.shopType') = 'BROWSE' THEN 1 END) AS count_created_browse_shop,
    COUNT(CASE WHEN json_extract_scalar(payload_txt, '$.shopType') = 'EVENT' THEN 1 END) AS count_created_event_shop
FROM ww_csd_dl_tables.csd_site_traffic_rptr_event_log_vw e
JOIN invited_users iu ON iu.pg_cust_id = e.pg_cust_id
WHERE e.event_dt BETWEEN DATE '{start_dt}' AND DATE '{end_dt}'
  AND (e.assoc_ind = 'false' OR e.assoc_ind IS NULL)
  AND JSON_EXTRACT_SCALAR(e.payload_txt, '$.eventType') = 'SPARKY_CHAT_RECEIVE'
  AND JSON_EXTRACT_SCALAR(e.payload_txt, '$.responseType') = 'SHOP_MESSAGE'
"""

cur.execute(sql)
rows = cur.fetchall()
cols = [desc[0] for desc in cur.description]
created_shop_type = pd.DataFrame(rows, columns=cols)
created_shop_type.head()

Users that created a shop

,users_created_browse_shop,users_created_event_shop,sessn_created_browse_shop,sessn_created_event_shop,count_created_browse_shop,count_created_event_shop
0,77,82,82,84,98,108

## Customer usage Engagement Funnel Metric - Users, Session, Count with ATC / Add All to cart

In [ ]:
print("Users that did ATC/ Total ATCs")
sql = f"""
WITH invited_users AS (
SELECT DISTINCT pg_cust_acct_id AS pg_cust_id
FROM gpadata_analytics.{invited_users}),

atc_clicks as (SELECT event_dt, 
       pg_cust_id, 
       brwsr_sessn_cooke_val,
       actn_catg_nm,
       actn_sub_catg_nm,
       cntxt_nm,
       CAST(from_unixtime(cast(event_ts_epoch as double) / 1000) AT TIME ZONE 'America/Los_Angeles' AS timestamp) AS event_ts_epoch,
       json_extract_scalar(page_attr, '$.nm') AS page_nm,
       json_extract_scalar(payload_txt, '$.r') AS ref_page,
       json_extract_scalar(payload_txt, '$.overlayName') AS overlay_nm,
       COALESCE(json_extract_scalar(payload_txt, '$.itemDetails.itemId'), 
                json_extract_scalar(payload_txt, '$.itemId'),
                json_extract_scalar(payload_txt, '$.itemDetails.usitemId')) AS item_id,
       MAX(json_extract_scalar(payload_txt, '$.shopId')) shop_id
FROM ww_csd_dl_tables.csd_site_traffic_rptr_event_log_vw
WHERE event_dt BETWEEN DATE '{start_dt}' AND DATE '{end_dt}'
AND (assoc_ind = 'false' OR assoc_ind is null) -- Exclude the associates
AND actn_catg_nm = 'onClick'
AND actn_sub_catg_nm in ('addToCart', 'addAllToCart')
AND json_extract_scalar(page_attr, '$.nm') != 'arPlatform'
GROUP BY 1,2,3,4,5,6,7,8,9,10,11),

dedupe AS (SELECT a.*, 
          row_number() OVER (PARTITION BY a.pg_cust_id, brwsr_sessn_cooke_val, actn_sub_catg_nm, item_id ORDER BY shop_id DESC, overlay_nm DESC, event_ts_epoch) AS rn_atc, -- Remove duplicates add to carts
          row_number() OVER (PARTITION BY a.pg_cust_id, brwsr_sessn_cooke_val, actn_sub_catg_nm, cntxt_nm, shop_id, item_id ORDER BY event_ts_epoch) AS rn_aatc -- Remove duplicates add all to carts
FROM atc_clicks a
JOIN invited_users i
ON i.pg_cust_id = a.pg_cust_id)

SELECT 
    COUNT(DISTINCT a.pg_cust_id) AS cust_w_atc_both,
    COUNT(DISTINCT CASE WHEN actn_sub_catg_nm = 'addAllToCart' THEN a.pg_cust_id END) AS cust_w_aatc,
    COUNT(DISTINCT CASE WHEN actn_sub_catg_nm = 'addToCart' THEN a.pg_cust_id END) AS cust_w_atc,
    COUNT(DISTINCT brwsr_sessn_cooke_val) AS sessn_w_atc_both,
    COUNT(DISTINCT CASE WHEN actn_sub_catg_nm = 'addAllToCart' THEN a.brwsr_sessn_cooke_val END) AS sessn_w_aatc,
    COUNT(DISTINCT CASE WHEN actn_sub_catg_nm = 'addToCart' THEN a.brwsr_sessn_cooke_val END) AS sessn_w_atc,
    COUNT(*) AS total_atc,
    COUNT(CASE WHEN actn_sub_catg_nm = 'addAllToCart' THEN 1 END) AS count_w_aatc,
    COUNT(CASE WHEN actn_sub_catg_nm = 'addToCart' THEN 1 END) AS count_w_atc
FROM dedupe a
WHERE CASE WHEN actn_sub_catg_nm = 'addToCart' THEN rn_atc = 1 ELSE rn_aatc = 1 END
"""
cur.execute(sql)
rows = cur.fetchall()
cols = [desc[0] for desc in cur.description]  # extract column names
atc_users = pd.DataFrame(rows, columns=cols)
atc_users.head()

Users that did ATC/ Total ATCs

,cust_w_atc_both,cust_w_aatc,cust_w_atc,sessn_w_atc_both,sessn_w_aatc,sessn_w_atc,total_atc,count_w_aatc,count_w_atc
0,975,70,961,1611,71,1593,5398,71,5327

## Users and sessions that clicked on continue to checkout

In [ ]:
print("Users that clicked on continue to cart")

sql = f"""
WITH invited_users AS (
SELECT DISTINCT pg_cust_acct_id AS pg_cust_id
FROM gpadata_analytics.{invited_users})

SELECT
  COUNT(DISTINCT a.pg_cust_id) AS cust_w_checkout,
  COUNT(DISTINCT a.brwsr_sessn_cooke_val) AS sessn_w_checkout
FROM (SELECT DISTINCT pg_cust_id, brwsr_sessn_cooke_val FROM ww_csd_dl_tables.csd_site_traffic_rptr_event_log_vw
WHERE event_dt BETWEEN DATE '{start_dt}' AND DATE '{end_dt}'
AND (assoc_ind = 'false' OR assoc_ind is null) -- Exclude the associates
AND actn_catg_nm IN ('onClick') 
AND actn_sub_catg_nm = 'continueToCheckout'
AND cntxt_nm = 'cart') a -- This will exclude the onboarding events
JOIN invited_users i
ON i.pg_cust_id = a.pg_cust_id -- To only keep the invited users

"""

cur.execute(sql)
rows = cur.fetchall()
cols = [desc[0] for desc in cur.description]   # extract column names
checkout_users = pd.DataFrame(rows, columns=cols)
checkout_users.head()

Users that clicked on continue to cart

   cust_w_checkout  sessn_w_checkout
0              451               590

## Customer Usage Engagement Funnel - Users, Sessions that had an order / Total orders

In [ ]:
print("Users that placed an order/ Total orders")

sql = f"""
WITH invited_users AS (
SELECT DISTINCT pg_cust_acct_id AS pg_cust_id
FROM gpadata_analytics.{invited_users})

SELECT
  COUNT(DISTINCT a.pg_cust_id) AS cust_w_orders,
  COUNT(DISTINCT a.brwsr_sessn_cooke_val) AS sessn_w_orders,
  COUNT(DISTINCT order_id) as total_orders
FROM (SELECT DISTINCT event_dt,
                 pg_cust_id, 
                 brwsr_sessn_cooke_val,
                 json_extract_scalar(payload_txt, '$.orderId') as order_id
      FROM ww_csd_dl_tables.csd_site_traffic_rptr_event_log_vw
      WHERE event_dt BETWEEN DATE '{start_dt}' AND DATE '{end_dt}'
      AND (assoc_ind = 'false' OR assoc_ind is null) -- Exclude the associates
      AND cntxt_nm = 'checkout'
      AND json_extract_scalar(page_attr, '$.nm') = 'thankYou'
      AND actn_catg_nm = 'pageView') a -- This will exclude the onboarding events
JOIN invited_users i
ON i.pg_cust_id = a.pg_cust_id -- To only keep the invited users
"""

cur.execute(sql)
rows = cur.fetchall()
cols = [desc[0] for desc in cur.description]   # extract column names
order_users = pd.DataFrame(rows, columns=cols)
order_users.head()

Users that placed an order/ Total orders

   cust_w_orders  sessn_w_orders  total_orders
0            319             392           399

## Customer Usage Engagement Funnel - Customers with repeated orders.

In [ ]:
print("Customers with repeated orders (more than one order)")

sql = f"""
WITH invited_users AS (
    SELECT DISTINCT pg_cust_acct_id AS pg_cust_id
    FROM gpadata_analytics.{invited_users}
),
orders_by_user AS (
    SELECT
        e.pg_cust_id,
        COUNT(DISTINCT JSON_EXTRACT_SCALAR(e.payload_txt, '$.orderId')) AS total_orders
    FROM ww_csd_dl_tables.csd_site_traffic_rptr_event_log_vw e
    JOIN invited_users iu ON iu.pg_cust_id = e.pg_cust_id
    WHERE e.event_dt BETWEEN DATE '{start_dt}' AND DATE '{end_dt}'
      AND (e.assoc_ind = 'false' OR e.assoc_ind IS NULL)
      AND e.cntxt_nm = 'checkout'
      AND JSON_EXTRACT_SCALAR(e.page_attr, '$.nm') = 'thankYou'
      AND e.actn_catg_nm = 'pageView'
    GROUP BY e.pg_cust_id
)
SELECT
    COUNT(Distinct pg_cust_id) AS users_with_repeated_orders
FROM orders_by_user
WHERE total_orders > 1
"""

cur.execute(sql)
rows = cur.fetchall()
cols = [desc[0] for desc in cur.description]
repeated_order_users = pd.DataFrame(rows, columns=cols)
repeated_order_users.head()

Customers with repeated orders (more than one order)

   users_with_repeated_orders
0                          60

## Metric - In Chat Bounced Users

In [ ]:
print("In Chat Bounced Users")

sql = f"""
WITH invited_users AS (
SELECT DISTINCT pg_cust_acct_id AS pg_cust_id
FROM gpadata_analytics.{invited_users}),

clicked_on_sparky AS (
    SELECT DISTINCT 
        pg_cust_id, 
        brwsr_sessn_cooke_val
    FROM ww_csd_dl_tables.csd_site_traffic_rptr_event_log_vw
    WHERE event_dt BETWEEN DATE '{start_dt}' AND DATE '{end_dt}'
    AND (assoc_ind = 'false' OR assoc_ind is null) -- Exclude the associates
    AND actn_catg_nm = 'onClick'
    AND actn_sub_catg_nm = 'sparky'
),

sent_msg AS (
    SELECT DISTINCT 
        pg_cust_id, 
        brwsr_sessn_cooke_val
    FROM ww_csd_dl_tables.csd_site_traffic_rptr_event_log_vw
    WHERE event_dt BETWEEN DATE '{start_dt}' AND DATE '{end_dt}'
    AND (assoc_ind = 'false' OR assoc_ind is null) -- Exclude the associates
    AND json_extract_scalar(payload_txt, '$.eventType') = 'SPARKY_CHAT_SEND'
)


SELECT COUNT(DISTINCT a.pg_cust_id) AS chat_bounce_users,
       COUNT(DISTINCT a.brwsr_sessn_cooke_val) AS chat_bounce_sessn
FROM clicked_on_sparky a
LEFT JOIN sent_msg b 
ON a.pg_cust_id = b.pg_cust_id AND a.brwsr_sessn_cooke_val = b.brwsr_sessn_cooke_val
JOIN invited_users i
ON i.pg_cust_id = a.pg_cust_id -- To only keep the invited users
WHERE b.brwsr_sessn_cooke_val is null
"""

cur.execute(sql)
rows = cur.fetchall()
cols = [desc[0] for desc in cur.description]   # extract column names
inchat_bounce_users = pd.DataFrame(rows, columns=cols)
inchat_bounce_users.head()

In Chat Bounced Users

   chat_bounce_users  chat_bounce_sessn
0                204                215

## Customer Usage - Message by Agents

In [ ]:
print("Messages by Agents")

final_agent_summary = load_bq_data(f"""
WITH invited_users AS (
  SELECT DISTINCT pg_cust_acct_id AS pg_cust_id
  FROM `wmt-et-ccomm-prod.temp.{invited_users}`
),

base_data AS (
  SELECT 
    ds,
    context_id,
    conversation_id,
    correlation_id,
    timestamp,
    session_id,
    consumer_id,
    input_text,
    converse_long_reply,
    converse_short_reply,
    cortex_intent,
    converse_intent,
    message,
    converse_response,
    cortex_agent_info,
    customer_id,
    channel_id
  FROM `wmt-et-converse-prod.converse_logs_ds_xrsamurai.logs_parsed`
  JOIN invited_users ON invited_users.pg_cust_id = customer_id
  WHERE DATE(DATETIME(TIMESTAMP(timestamp), 'America/Los_Angeles')) 
            BETWEEN '{start_dt}' AND '{end_dt}'
    AND cortex_agent_info IS NOT NULL
    AND cortex_agent_info != ''
    AND channel_id = 'RAPTOR_IOS_APP'
),

agents_extracted AS (
  SELECT
    *,
    ARRAY(
      SELECT agent_key
      FROM UNNEST(REGEXP_EXTRACT_ALL(cortex_agent_info, r'"(a\\d+)"\\s*:')) AS agent_key
    ) AS agent_keys,
    ARRAY(
      SELECT id
      FROM UNNEST(REGEXP_EXTRACT_ALL(cortex_agent_info, r'"id"\\s*:\\s*"([^"]+)"')) AS id
    ) AS agent_names,
    ARRAY(
      SELECT model
      FROM UNNEST(REGEXP_EXTRACT_ALL(cortex_agent_info, r'"model"\\s*:\\s*"([^"]+)"')) AS model
    ) AS all_models
  FROM base_data
),

final_agent_calc AS (
  SELECT
    *,
    ARRAY_LENGTH(agent_names) AS total_agents,
    ARRAY_TO_STRING(agent_keys, ' → ') AS agent_keys_flow,
    ARRAY_TO_STRING(agent_names, ' → ') AS agent_names_flow,
    (
      SELECT agent_name
      FROM UNNEST(agent_names) AS agent_name WITH OFFSET pos
      WHERE agent_name IS NOT NULL
        AND NOT STARTS_WITH(agent_name, 'condition_')
        AND agent_name NOT IN (
          'shelving_arrangement',
          'unifiedbrowseshopapiagent',
          'unifiedeventshopparserapiagent',
          'router',
          'rootrouteragent',
          'conversation_title_generator'
        )
      ORDER BY pos DESC
      LIMIT 1
    ) AS final_answer_agent
  FROM agents_extracted
),

final_query AS (
  SELECT
    ds,
    timestamp,
    conversation_id,
    correlation_id,
    cortex_agent_info,
    input_text,
    SUBSTR(message, 1, 100) AS message_preview,
    agent_keys,
    agent_names,
    agent_keys_flow,
    agent_names_flow,
    total_agents,
    final_answer_agent
  FROM final_agent_calc
)

SELECT 

  COUNT(DISTINCT CASE 
      WHEN final_answer_agent IN ('essentials_suggestion_chips_generator','essentials_shop_suggestion_chips_generator','essentials') THEN correlation_id END
  ) AS essentials_shopping_planner_agent,

  COUNT(DISTINCT CASE 
      WHEN final_answer_agent LIKE 'event%' THEN correlation_id END
  ) AS events_shopping_planner_agent,

  COUNT(DISTINCT CASE 
      WHEN final_answer_agent IN ('visual_product_comparisons') THEN correlation_id END
  ) AS product_comparison_search_agent,

  COUNT(DISTINCT CASE 
      WHEN final_answer_agent LIKE 'browse%' THEN correlation_id END
  ) AS browse_shopping_planner_agent,

  COUNT(DISTINCT CASE 
      WHEN final_answer_agent IN ('item_question_answering') THEN correlation_id END
  ) AS item_question_answering_agent,

  COUNT(DISTINCT CASE 
      WHEN final_answer_agent IN ('sparky_ccare_rag') THEN correlation_id END
  ) AS sparky_ccare_rag_agent,

  COUNT(DISTINCT CASE 
      WHEN final_answer_agent IN ('general_knowledge') THEN correlation_id END
  ) AS general_knowledge_agent,

  COUNT(DISTINCT CASE 
      WHEN final_answer_agent IN ('generic_fallback','fallback_agent') THEN correlation_id END
  ) AS fallback_agent,

  COUNT(DISTINCT CASE 
      WHEN final_answer_agent IN ('essentials_manager') THEN correlation_id END
  ) AS essentials_manager_agent,

FROM final_query
""")

final_agent_summary.head()

Messages by Agents

,essentials_shopping_planner_agent,events_shopping_planner_agent,product_comparison_search_agent,browse_shopping_planner_agent,item_question_answering_agent,sparky_ccare_rag_agent,general_knowledge_agent,fallback_agent,essentials_manager_agent
0,115,264,9813,118,68,80,77,377,3

## System Performance - Total Messages, Error, Fallback

In [ ]:
print("Total Messages, Error, Fallback")

inchat_msg = load_bq_data(f"""
                   WITH invited_users AS (
                    SELECT DISTINCT pg_cust_acct_id AS pg_cust_id
                    FROM `wmt-et-ccomm-prod.temp.{invited_users}`)

                  SELECT
                  COUNT(DISTINCT correlation_id) AS total_msg,
                  COUNT(DISTINCT CASE WHEN REGEXP_EXTRACT(current_entities, '\\\\{{([^=]+)=' ) = 'fallback_category' THEN correlation_id END) AS fallback_msg,
                  COUNT(DISTINCT CASE WHEN converse_intent is null
                                      OR converse_intent = ""
                                      OR converse_short_reply like "%Sorry, there was a problem while processing your request. Can I help you with anything else?%"
                                      OR converse_short_reply like "%Your user id is already in use. Please try again after sometime.%"
                                      OR converse_short_reply like "%not quite working on my end, please try again later.%"
                                      THEN correlation_id END) AS error_msg
                  FROM `wmt-et-converse-prod.converse_logs_ds_xrsamurai.logs_parsed` a
                  JOIN invited_users i
                  ON i.pg_cust_id = a.customer_id -- To only keep the invited users
                  WHERE DATE(DATETIME(TIMESTAMP(timestamp), 'America/Los_Angeles')) BETWEEN '{start_dt}' AND '{end_dt}'
                  AND channel_id = 'RAPTOR_IOS_APP'
                    """)

inchat_msg.head()

Total Messages, Error, Fallback

   total_msg  fallback_msg  error_msg
0      11092           372        258

## System Performance - Latency (p50, p75, p90, p95, p99)

In [ ]:
print("Latency Percentiles (p50, p75, p90, p95, p99)")

latency_percentiles = load_bq_data(f"""
    WITH invited_users AS (
        SELECT DISTINCT pg_cust_acct_id AS pg_cust_id
        FROM `wmt-et-ccomm-prod.temp.{invited_users}`
    ),
    ml_json AS (
        SELECT
            correlation_id,
            CASE
                WHEN REGEXP_CONTAINS(customMetadata, r'"module_latency":"\\{{') THEN
                    REPLACE(JSON_EXTRACT_SCALAR(customMetadata, '$.module_latency'), '\\\\', '')
                ELSE
                    JSON_EXTRACT(customMetadata, '$.module_latency')
            END AS ml_clean
        FROM `wmt-et-converse-prod.converse_logs_ds_xrsamurai.logs_parsed` a
        JOIN invited_users i ON i.pg_cust_id = a.customer_id
        WHERE DATE(DATETIME(TIMESTAMP(a.timestamp), 'America/Los_Angeles')) BETWEEN '{start_dt}' AND '{end_dt}'
            AND a.channel_id = 'RAPTOR_IOS_APP'
    ),
    latency AS (
        SELECT
            correlation_id,
            IFNULL(
                SUM(CAST(REGEXP_EXTRACT(pair, r'"[^"]+":"(\\d+)"') AS INT64)), 0
            )/1000.0 AS total_latency_sec
        FROM ml_json,
            UNNEST(REGEXP_EXTRACT_ALL(ml_clean, r'"[^"]+":"\\d+"')) AS pair
        WHERE
            ml_clean IS NOT NULL
            AND ml_clean != '{{}}'
            AND REGEXP_EXTRACT(pair, r'"([^"]+)":') != 'xrsamurai:CortexService'
        GROUP BY correlation_id
    )
    SELECT
        APPROX_QUANTILES(total_latency_sec, 100)[OFFSET(50)] AS p50_latency,
        APPROX_QUANTILES(total_latency_sec, 100)[OFFSET(75)] AS p75_latency,
        APPROX_QUANTILES(total_latency_sec, 100)[OFFSET(90)] AS p90_latency,
        APPROX_QUANTILES(total_latency_sec, 100)[OFFSET(95)] AS p95_latency,
        APPROX_QUANTILES(total_latency_sec, 100)[OFFSET(99)] AS p99_latency
    FROM latency
""")

latency_percentiles.head()

Latency Percentiles (p50, p75, p90, p95, p99)

   p50_latency  p75_latency  p90_latency  p95_latency  p99_latency
0        8.378        9.467       10.725       11.728       18.541

## Interaction Experience - Duration of Session

In [ ]:
print("Average, Min, and Max Session Duration (ms and seconds)")

sql = f"""
WITH invited_users AS (
    SELECT DISTINCT pg_cust_acct_id AS pg_cust_id
    FROM gpadata_analytics.{invited_users}
),
session_durations AS (
    SELECT
        brwsr_sessn_cooke_val AS session_id,
        CAST(MIN(CAST(event_ts_epoch AS BIGINT)) AS BIGINT) AS min_ts,
        CAST(MAX(CAST(event_ts_epoch AS BIGINT)) AS BIGINT) AS max_ts,
        MAX(CAST(event_ts_epoch AS BIGINT)) - MIN(CAST(event_ts_epoch AS BIGINT)) AS session_duration_ms
    FROM ww_csd_dl_tables.csd_site_traffic_rptr_event_log_vw e
    JOIN invited_users iu ON iu.pg_cust_id = e.pg_cust_id
    WHERE e.event_dt BETWEEN DATE '{start_dt}' AND DATE '{end_dt}'
    GROUP BY brwsr_sessn_cooke_val
)
SELECT
    ROUND(AVG(session_duration_ms) / 1000, 2) AS avg_session_duration_sec,
    ROUND(MIN(session_duration_ms) / 1000, 2) AS min_session_duration_sec,
    ROUND(MAX(session_duration_ms) / 1000, 2) AS max_session_duration_sec
FROM session_durations
WHERE session_duration_ms > 0
"""

cur.execute(sql)
rows = cur.fetchall()
cols = [desc[0] for desc in cur.description]
session_duration = pd.DataFrame(rows, columns=cols)
session_duration.head()

Average, Min, and Max Session Duration (ms and seconds)

,avg_session_duration_sec,min_session_duration_sec,max_session_duration_sec
0,265.78,0,45251

## Users with Carousel Impressions, Total Carousel Impressions and Total Item Impressions

In [ ]:
print("Users with item carousel impressions")


users_w_carousel_imp = load_bq_data(f"""
WITH invited_users AS (
 SELECT DISTINCT pg_cust_acct_id AS pg_cust_id
 FROM `wmt-et-ccomm-prod.temp.{invited_users}`),

carousel AS (SELECT 
*,
REGEXP_EXTRACT(current_entities, r'products=\[([\s\S]*?)\]') AS products_inner
FROM `wmt-et-converse-prod.converse_logs_ds_xrsamurai.logs_parsed` a
JOIN invited_users i
ON i.pg_cust_id = a.customer_id -- To only keep the invited users
WHERE DATE(DATETIME(TIMESTAMP(timestamp), 'America/Los_Angeles')) BETWEEN '{start_dt}' AND '{end_dt}'
AND channel_id = 'RAPTOR_IOS_APP'
AND REGEXP_EXTRACT(current_entities, r'products=\[([\s\S]*?)\]') is Not Null),

carousel_item AS (SELECT
 customer_id,
 correlation_id,
 ARRAY_AGG(JSON_EXTRACT_SCALAR(product, '$.usItemId')) AS usItemIds,
 ARRAY_LENGTH(ARRAY_AGG(JSON_EXTRACT_SCALAR(product, '$.usItemId'))) AS usItemCount
FROM carousel,
UNNEST(JSON_EXTRACT_ARRAY(CONCAT('[', products_inner, ']'), '$')) AS product
WHERE products_inner IS NOT NULL
GROUP BY 1, 2)

SELECT COUNT(DISTINCT customer_id) users_w_carousel_imp, Count(Distinct correlation_id) as carousel_imp
FROM carousel
""")

users_w_carousel_imp.head()

Users with item carousel impressions

RetryError: Timeout of 600.0s exceeded, last exception: Timeout of 600.0s exceeded, last exception: ('Connection aborted.', ConnectionAbortedError(10053, 'An established connection was aborted by the software in your host machine', None, 10053, None))

## Shop Engagement Funnel by Volume - PDP page Impressions

In [ ]:
print("Total Product Page Inmpressions")

sql = f"""
WITH invited_users AS (
    SELECT DISTINCT pg_cust_acct_id AS pg_cust_id
    FROM gpadata_analytics.{invited_users}
),

impressions AS (
    SELECT *,
        json_extract_scalar(payload_txt, '$.pageViewId') AS pageViewId,
        json_extract_scalar(page_attr, '$.nm') AS page_nm
    FROM ww_csd_dl_tables.csd_site_traffic_rptr_event_log_vw e
    JOIN invited_users iu ON iu.pg_cust_id = e.pg_cust_id
    WHERE e.event_dt BETWEEN DATE '{start_dt}' AND DATE '{end_dt}'
      AND (e.assoc_ind = 'false' OR e.assoc_ind IS NULL)
      AND e.actn_catg_nm = 'pageView'
      ---AND e.cntxt_nm IN ('eventShop', 'weeklyShop', 'browseShop', 'categoryShop', 'cart', 'orderDetails', 'discoverMore')
)

SELECT
    COUNT(DISTINCT CASE 
        WHEN (cntxt_nm = 'productPage' AND page_nm = 'productPage')
        THEN pageViewId END) AS productPage_impressions
FROM impressions
"""

cur.execute(sql)
rows = cur.fetchall()
cols = [desc[0] for desc in cur.description]
pdp_imp = pd.DataFrame(rows, columns=cols)
pdp_imp.head()

Total Product Page Inmpressions

   productPage_impressions
0                    93523

In [ ]:
print("Funnel reach metrics for shops (Impression, Message, PDP click, ATC, AddAllToCart, PDP-ATC, Combined ATC)")

sql = f"""
WITH invited_users AS (
    SELECT DISTINCT pg_cust_acct_id AS pg_cust_id
    FROM gpadata_analytics.{invited_users}
),

-- Pageview events CTE
filtered_pageviews AS (
    SELECT
        a.pg_cust_id,
        a.brwsr_sessn_cooke_val,
        a.cntxt_nm,
        json_extract_scalar(a.page_attr, '$.nm' ) AS page_name,
        json_extract_scalar(a.payload_txt, '$.shopId' ) AS shop_id,
        json_extract_scalar(payload_txt, '$.pageViewId') as pageViewId,
        json_extract_scalar(payload_txt, '$.r') AS ref_page,
        a.event_dt,
        CAST(from_unixtime(cast(event_ts_epoch as double) / 1000) AT TIME ZONE 'America/Los_Angeles' AS timestamp) AS event_ts
    FROM ww_csd_dl_tables.csd_site_traffic_rptr_event_log_vw a
    JOIN invited_users i ON i.pg_cust_id = a.pg_cust_id
    WHERE event_dt BETWEEN DATE '{start_dt}' AND DATE '{end_dt}'
        AND (a.assoc_ind = 'false' OR a.assoc_ind IS NULL)
        AND a.actn_catg_nm = 'moduleView'
        AND json_extract_scalar(a.payload_txt, '$.moduleName' ) = 'itemZone'
        AND a.cntxt_nm IN ('eventShop', 'weeklyShop' , 'browseShop', 'categoryShop' )
),

shop_pageviews AS (
    SELECT
        pg_cust_id,
        brwsr_sessn_cooke_val,
        cntxt_nm,
        page_name,
        shop_id,
        event_dt,
        event_ts,
        'openShop' AS actn_catg_nm,
        NULL AS actn_sub_catg_nm,
        pageViewId,
        ref_page,
        NULL AS overlay_nm,
        NULL AS item_id,
        'imp' AS source_type,
        ROW_NUMBER() OVER (
            PARTITION BY pg_cust_id, brwsr_sessn_cooke_val, cntxt_nm, page_name, shop_id
            ORDER BY event_ts
        ) AS page_view_rank
    FROM filtered_pageviews
),

-- Item clicks CTE
item_clicks AS (
    SELECT DISTINCT
        a.pg_cust_id,
        brwsr_sessn_cooke_val,
        cntxt_nm,
        json_extract_scalar(page_attr, '$.nm') AS page_name,
        json_extract_scalar(payload_txt, '$.shopId') AS shop_id,
        event_dt,
        CAST(from_unixtime(cast(event_ts_epoch as double) / 1000) AT TIME ZONE 'America/Los_Angeles' AS timestamp) AS event_ts,
        actn_catg_nm,
        actn_sub_catg_nm,
        json_extract_scalar(payload_txt, '$.pageViewId') as pageViewId,
        json_extract_scalar(payload_txt, '$.r') AS ref_page,
        json_extract_scalar(payload_txt, '$.overlayName') AS overlay_nm,
        COALESCE(json_extract_scalar(payload_txt, '$.itemDetails.itemId'), 
                json_extract_scalar(payload_txt, '$.itemId'),
                json_extract_scalar(payload_txt, '$.itemDetails.usitemId')) AS item_id,
        'itemclick' AS source_type, -- now 3 for item clicks
        NULL AS page_view_rank
    FROM ww_csd_dl_tables.csd_site_traffic_rptr_event_log_vw a 
    JOIN invited_users i ON i.pg_cust_id = a.pg_cust_id
    WHERE event_dt BETWEEN DATE '{start_dt}' AND DATE '{end_dt}'
        AND (assoc_ind = 'false' OR assoc_ind IS NULL)
        AND actn_sub_catg_nm = 'itemClick'
        AND cntxt_nm IN ('eventShop', 'weeklyShop' , 'browseShop', 'categoryShop')
),

-- ATC Clicks CTE (deduped)
atc_clicks AS (
    SELECT
        event_dt, 
        pg_cust_id, 
        brwsr_sessn_cooke_val,
        actn_catg_nm,
        actn_sub_catg_nm,
        cntxt_nm,
        CAST(from_unixtime(cast(event_ts_epoch as double) / 1000) AT TIME ZONE 'America/Los_Angeles' AS timestamp) AS event_ts,
        json_extract_scalar(page_attr, '$.nm') AS page_name,
        MAX(json_extract_scalar(payload_txt, '$.shopId')) AS shop_id,
        json_extract_scalar(payload_txt, '$.pageViewId') as pageViewId,
        json_extract_scalar(payload_txt, '$.r') AS ref_page,
        json_extract_scalar(payload_txt, '$.overlayName') AS overlay_nm,
        COALESCE(json_extract_scalar(payload_txt, '$.itemDetails.itemId'), 
                json_extract_scalar(payload_txt, '$.itemId'),
                json_extract_scalar(payload_txt, '$.itemDetails.usitemId')) AS item_id
    FROM ww_csd_dl_tables.csd_site_traffic_rptr_event_log_vw
    WHERE event_dt BETWEEN DATE '{start_dt}' AND DATE '{end_dt}'
        AND (assoc_ind = 'false' OR assoc_ind IS NULL)
        AND actn_catg_nm = 'onClick'
        AND actn_sub_catg_nm in ('addToCart', 'addAllToCart')
        AND json_extract_scalar(page_attr, '$.nm') != 'arPlatform'
    GROUP BY 1,2,3,4,5,6,7,8,10,11,12,13
),

deduped_atc AS (
    SELECT a.*,
        ROW_NUMBER() OVER (PARTITION BY a.pg_cust_id, a.brwsr_sessn_cooke_val, a.actn_sub_catg_nm, a.item_id ORDER BY a.shop_id DESC, a.overlay_nm DESC, a.event_ts) AS rn_atc,
        ROW_NUMBER() OVER (PARTITION BY a.pg_cust_id, a.brwsr_sessn_cooke_val, a.actn_sub_catg_nm, a.cntxt_nm, a.shop_id, a.item_id ORDER BY a.event_ts) AS rn_aatc
    FROM atc_clicks a
    JOIN invited_users i ON i.pg_cust_id = a.pg_cust_id
),

final_atc AS (
    SELECT
        pg_cust_id,
        brwsr_sessn_cooke_val,
        cntxt_nm,
        page_name,
        shop_id,
        event_dt,
        event_ts,
        actn_catg_nm,
        actn_sub_catg_nm,
        pageViewId,
        ref_page,
        overlay_nm,
        item_id,
        'atc' AS source_type, -- now 2 for atc
        Null as page_view_rank
    FROM deduped_atc
    WHERE CASE WHEN actn_sub_catg_nm = 'addToCart' THEN rn_atc = 1 ELSE rn_aatc = 1 END
    AND cntxt_nm IN ('eventShop', 'weeklyShop' , 'browseShop', 'categoryShop') 
    and overlay_nm is Null 
    or (cntxt_nm = 'productPage' and ref_page In ('eventShop', 'weeklyShop' , 'browseShop', 'categoryShop'))
),

messages AS (
    
SELECT  
        a.pg_cust_id, 
        brwsr_sessn_cooke_val,
        cntxt_nm,
        json_extract_scalar(page_attr, '$.nm') AS page_name,
        json_extract_scalar(a.payload_txt, '$.shopId' ) AS shop_id,
        event_dt,
        -- Use event_ts for ordering
        CAST(from_unixtime(cast(event_ts_epoch as double) / 1000) AT TIME ZONE 'America/Los_Angeles' AS timestamp) AS event_ts,
        'message' as actn_catg_nm,
        actn_sub_catg_nm,
        json_extract_scalar(payload_txt, '$.pageViewId') as pageViewId,
        json_extract_scalar(payload_txt, '$.r') AS ref_page,
        json_extract_scalar(payload_txt, '$.overlayName') AS overlay_nm,
        Null AS item_id,
        'msg' AS source_type, -- 4 for message events
        NULL AS page_view_rank
    FROM ww_csd_dl_tables.csd_site_traffic_rptr_event_log_vw a
    JOIN invited_users i ON i.pg_cust_id = a.pg_cust_id
    WHERE event_dt BETWEEN DATE '{start_dt}' AND DATE '{end_dt}'
        AND (assoc_ind = 'false' OR assoc_ind IS NULL)
        AND json_extract_scalar(payload_txt, '$.buttonName') = 'sendSparkyChat'
        AND cntxt_nm IN ('eventShop', 'weeklyShop' , 'browseShop', 'categoryShop')
),

-- Final union and sort
all_events as (
SELECT
    pg_cust_id,
    brwsr_sessn_cooke_val,
    cntxt_nm,
    page_name,
    shop_id,
    event_dt,
    event_ts,
    actn_catg_nm,
    actn_sub_catg_nm,
    pageViewId,
    ref_page,
    overlay_nm,
    item_id,
    source_type,
    page_view_rank
FROM shop_pageviews

UNION ALL

SELECT
    pg_cust_id,
    brwsr_sessn_cooke_val,
    cntxt_nm,
    page_name,
    shop_id,
    event_dt,
    event_ts,
    actn_catg_nm,
    actn_sub_catg_nm,
    pageViewId,
    ref_page,
    overlay_nm,
    item_id,
    source_type,
    page_view_rank
FROM final_atc

UNION ALL

SELECT
    pg_cust_id,
    brwsr_sessn_cooke_val,
    cntxt_nm,
    page_name,
    shop_id,
    event_dt,
    event_ts,
    actn_catg_nm,
    actn_sub_catg_nm,
    pageViewId,
    ref_page,
    overlay_nm,
    item_id,
    source_type,
    page_view_rank
FROM item_clicks

UNION ALL

SELECT
    pg_cust_id,
    brwsr_sessn_cooke_val,
    cntxt_nm,
    page_name,
    shop_id,
    event_dt,
    event_ts,
    actn_catg_nm,
    actn_sub_catg_nm,
    pageViewId,
    ref_page,
    overlay_nm,
    item_id,
    source_type,
    page_view_rank
FROM messages


ORDER BY
    pg_cust_id,
    brwsr_sessn_cooke_val,
    event_dt,
    event_ts
),


final as (SELECT
    pg_cust_id,
    brwsr_sessn_cooke_val,
    cntxt_nm,
    page_name,
    shop_id,
    -- This fills down the most recent non-null shop_id in each session/date group
    MAX(CASE WHEN shop_id IS NOT NULL THEN shop_id END)
        OVER (
            PARTITION BY pg_cust_id, brwsr_sessn_cooke_val, event_dt
            ORDER BY event_ts
            ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
        ) AS shop_id_filled,
    event_dt,
    event_ts,
    actn_catg_nm,
    actn_sub_catg_nm,
    pageViewId,
    ref_page,
    overlay_nm,
    item_id,
    source_type,
    page_view_rank
FROM all_events
ORDER BY pg_cust_id, brwsr_sessn_cooke_val, event_dt, event_ts)


SELECT
    ---------------------------Impresion of unique shop per session-------------------
        COUNT(DISTINCT CASE 
        WHEN cntxt_nm = 'browseShop' AND page_name = 'browseShop' and actn_catg_nm = 'openShop'
        THEN brwsr_sessn_cooke_val || '-' || shop_id_filled
    END) AS browse_shop_imp_reach,
    COUNT(DISTINCT CASE 
        WHEN cntxt_nm = 'eventShop' AND page_name = 'eventShop' and actn_catg_nm = 'openShop'
        THEN brwsr_sessn_cooke_val || '-' || shop_id_filled
    END) AS event_shop_imp_reach,
    COUNT(DISTINCT CASE 
        WHEN cntxt_nm = 'weeklyShop' AND page_name = 'weeklyShop' and actn_catg_nm = 'openShop'
        THEN brwsr_sessn_cooke_val || '-' || shop_id_filled
    END) AS weekly_shop_imp_reach,
    COUNT(DISTINCT CASE 
        WHEN cntxt_nm = 'categoryShop' AND page_name = 'categoryShop' and actn_catg_nm = 'openShop'
        THEN brwsr_sessn_cooke_val || '-' || shop_id_filled
    END) AS category_shop_imp_reach,
    
    ----------------------------atleast one message sent per shop per session----------------------
    COUNT(DISTINCT CASE 
        WHEN cntxt_nm = 'browseShop' AND page_name = 'browseShop' and actn_catg_nm = 'message'
        THEN brwsr_sessn_cooke_val || '-' || shop_id_filled
    END) AS browse_shop_msg_reach,

    COUNT(DISTINCT CASE 
        WHEN cntxt_nm = 'eventShop' AND page_name = 'eventShop' and actn_catg_nm = 'message'
        THEN brwsr_sessn_cooke_val || '-' || shop_id_filled
    END) AS event_shop_msg_reach,

    COUNT(DISTINCT CASE 
        WHEN cntxt_nm = 'weeklyShop' AND page_name = 'weeklyShop' and actn_catg_nm = 'message'
        THEN brwsr_sessn_cooke_val || '-' || shop_id_filled
    END) AS weekly_shop_msg_reach,
    COUNT(DISTINCT CASE 
        WHEN cntxt_nm = 'categoryShop' AND page_name = 'categoryShop' and actn_catg_nm = 'message'
        THEN brwsr_sessn_cooke_val || '-' || shop_id_filled
    END) AS category_shop_msg_reach,
    
    ----------------------------atleast one item Click per shop per session------------------------
    COUNT(DISTINCT CASE 
        WHEN cntxt_nm = 'browseShop' AND page_name = 'browseShop' and actn_sub_catg_nm = 'itemClick'
        THEN brwsr_sessn_cooke_val || '-' || shop_id_filled
    END) AS browse_shop_PDPclicks_reach,

    COUNT(DISTINCT CASE 
        WHEN cntxt_nm = 'eventShop' AND page_name = 'eventShop' and actn_sub_catg_nm = 'itemClick'
        THEN brwsr_sessn_cooke_val || '-' || shop_id_filled
    END) AS event_shop_PDPclicks_reach,

    COUNT(DISTINCT CASE 
        WHEN cntxt_nm = 'weeklyShop' AND page_name = 'weeklyShop' and actn_sub_catg_nm = 'itemClick'
        THEN brwsr_sessn_cooke_val || '-' || shop_id_filled
    END) AS weekly_shop_PDPclicks_reach,

    COUNT(DISTINCT CASE 
        WHEN cntxt_nm = 'categoryShop' AND page_name = 'categoryShop' and actn_sub_catg_nm = 'itemClick'
        THEN brwsr_sessn_cooke_val || '-' || shop_id_filled
    END) AS category_shop_PDPclicks_reach,

	
	 -- Combined ATC reach per session, per shop type (direct ATC, addAllToCart, or PDP ATC)
    COUNT(DISTINCT CASE 
        WHEN 
            (
                (cntxt_nm = 'browseShop' AND page_name = 'browseShop' AND actn_sub_catg_nm = 'addToCart')
                OR
                (cntxt_nm = 'browseShop' AND page_name = 'browseShop' AND actn_sub_catg_nm = 'addAllToCart')
                OR
                (cntxt_nm = 'productPage' AND page_name = 'productPage' AND ref_page = 'browseShop' AND actn_sub_catg_nm = 'addToCart')
            )
        THEN brwsr_sessn_cooke_val || '-' || shop_id_filled
    END) AS browse_shop_combined_ATC_reach,

    COUNT(DISTINCT CASE 
        WHEN 
            (
                -- Direct ATC
                (cntxt_nm = 'eventShop' AND page_name = 'eventShop' AND actn_sub_catg_nm = 'addToCart')
                OR
                -- Add All to Cart
                (cntxt_nm = 'eventShop' AND page_name = 'eventShop' AND actn_sub_catg_nm = 'addAllToCart')
                OR
                -- PDP ATC for eventShop
                (cntxt_nm = 'productPage' AND page_name = 'productPage' AND ref_page = 'eventShop' AND actn_sub_catg_nm = 'addToCart')
            )
        THEN brwsr_sessn_cooke_val || '-' || shop_id_filled
    END) AS event_shop_combined_ATC_reach,
    
    COUNT(DISTINCT CASE 
        WHEN 
            (
                (cntxt_nm = 'weeklyShop' AND page_name = 'weeklyShop' AND actn_sub_catg_nm = 'addToCart')
                OR
                (cntxt_nm = 'weeklyShop' AND page_name = 'weeklyShop' AND actn_sub_catg_nm = 'addAllToCart')
                OR
                (cntxt_nm = 'productPage' AND page_name = 'productPage' AND ref_page = 'weeklyShop' AND actn_sub_catg_nm = 'addToCart')
            )
        THEN brwsr_sessn_cooke_val || '-' || shop_id_filled
    END) AS weekly_shop_combined_ATC_reach,
    
    
    COUNT(DISTINCT CASE 
        WHEN 
            (
                (cntxt_nm = 'categoryShop' AND page_name = 'categoryShop' AND actn_sub_catg_nm = 'addToCart')
                OR
                (cntxt_nm = 'categoryShop' AND page_name = 'categoryShop' AND actn_sub_catg_nm = 'addAllToCart')
                OR
                (cntxt_nm = 'productPage' AND page_name = 'productPage' AND ref_page = 'categoryShop' AND actn_sub_catg_nm = 'addToCart')
            )
        THEN brwsr_sessn_cooke_val || '-' || shop_id_filled
    END) AS category_shop_combined_ATC_reach,
    
    -----------------------------at least one direct ATC per shop per session--------------------------
        COUNT(DISTINCT CASE 
        WHEN cntxt_nm = 'browseShop' AND page_name = 'browseShop' and actn_sub_catg_nm = 'addToCart'
        THEN brwsr_sessn_cooke_val || '-' || shop_id_filled
    END) AS browse_shop_ATC_reach,

    COUNT(DISTINCT CASE 
        WHEN cntxt_nm = 'eventShop' AND page_name = 'eventShop' and actn_sub_catg_nm = 'addToCart'
        THEN brwsr_sessn_cooke_val || '-' || shop_id_filled
    END) AS event_shop_ATC_reach,

    COUNT(DISTINCT CASE 
        WHEN cntxt_nm = 'weeklyShop' AND page_name = 'weeklyShop' and actn_sub_catg_nm = 'addToCart'
        THEN brwsr_sessn_cooke_val || '-' || shop_id_filled
    END) AS weekly_shop_ATC_reach,

    COUNT(DISTINCT CASE 
        WHEN cntxt_nm = 'categoryShop' AND page_name = 'categoryShop' and actn_sub_catg_nm = 'addToCart'
        THEN brwsr_sessn_cooke_val || '-' || shop_id_filled
    END) AS category_shop_ATC_reach,
    
    ---------------------------add all to cart per Shop per session---------------------------
        COUNT(DISTINCT CASE 
        WHEN cntxt_nm = 'eventShop' AND page_name = 'eventShop' and actn_sub_catg_nm = 'addAllToCart'
        THEN brwsr_sessn_cooke_val || '-' || shop_id_filled
    END) AS event_shop_AATC_reach,

    COUNT(DISTINCT CASE 
        WHEN cntxt_nm = 'weeklyShop' AND page_name = 'weeklyShop' and actn_sub_catg_nm = 'addAllToCart'
        THEN brwsr_sessn_cooke_val || '-' || shop_id_filled
    END) AS weekly_shop_AATC_reach,
    
    -----------------------------atleast one PDP ATC per shop per session--------------------------------
     COUNT(DISTINCT CASE WHEN cntxt_nm = 'productPage' AND page_name = 'productPage' AND ref_page = 'browseShop' AND actn_sub_catg_nm = 'addToCart'
    THEN brwsr_sessn_cooke_val || '-' || shop_id_filled
    END) AS browse_shop_PDPATC_reach,

    COUNT(DISTINCT CASE
    WHEN cntxt_nm = 'productPage' AND page_name = 'productPage'AND ref_page = 'eventShop' AND actn_sub_catg_nm = 'addToCart'
    THEN brwsr_sessn_cooke_val || '-' || shop_id_filled
    END) AS event_shop_PDPATC_reach,

    COUNT(DISTINCT CASE
    WHEN cntxt_nm = 'productPage' AND page_name = 'productPage' AND ref_page = 'weeklyShop' AND actn_sub_catg_nm = 'addToCart'
    THEN brwsr_sessn_cooke_val || '-' || shop_id_filled
    END) AS weekly_shop_PDPATC_reach,

  COUNT(DISTINCT CASE WHEN cntxt_nm = 'productPage' AND page_name = 'productPage' AND ref_page = 'categoryShop' AND actn_sub_catg_nm = 'addToCart'
    THEN brwsr_sessn_cooke_val || '-' || shop_id_filled
END) AS category_shop_PDPATC_reach

FROM final 
where shop_id_filled IS NOT NULL
"""


cur.execute(sql)
rows = cur.fetchall()
cols = [desc[0] for desc in cur.description]
shop_engagement_reach_metrics = pd.DataFrame(rows, columns=cols)
shop_engagement_reach_metrics.head()

Funnel reach metrics for shops (Impression, Message, PDP click, ATC, AddAllToCart, PDP-ATC, Combined ATC)

,browse_shop_imp_reach,event_shop_imp_reach,weekly_shop_imp_reach,category_shop_imp_reach,browse_shop_msg_reach,event_shop_msg_reach,weekly_shop_msg_reach,category_shop_msg_reach,browse_shop_PDPclicks_reach,event_shop_PDPclicks_reach,...,browse_shop_ATC_reach,event_shop_ATC_reach,weekly_shop_ATC_reach,category_shop_ATC_reach,event_shop_AATC_reach,weekly_shop_AATC_reach,browse_shop_PDPATC_reach,event_shop_PDPATC_reach,weekly_shop_PDPATC_reach,category_shop_PDPATC_reach
0,735,1383,5701,25301,114,130,637,7438,222,361,...,112,27,535,1814,126,754,36,8,82,1011

In [ ]:
print("Carousel Funnel Impressions Reach")

sql = f"""
WITH invited_users AS (
SELECT DISTINCT pg_cust_acct_id AS pg_cust_id
FROM gpadata_analytics.{invited_users}),

------------------- ITEM CLICKS -------------------
item_clicks AS (
    SELECT DISTINCT
        a.pg_cust_id,
        brwsr_sessn_cooke_val,
        event_dt,
        CAST(from_unixtime(cast(event_ts_epoch AS double) / 1000) 
             AT TIME ZONE 'America/Los_Angeles' AS timestamp) AS event_ts,
        json_extract_scalar(payload_txt, '$.shopId') AS shop_id,
        COALESCE(json_extract_scalar(payload_txt, '$.itemDetails.itemId'), 
                 json_extract_scalar(payload_txt, '$.itemId'),
                 json_extract_scalar(payload_txt, '$.itemDetails.usitemId')) AS item_id,
        json_extract_scalar(payload_txt, '$.pageViewId') as pageViewId,
        json_extract_scalar(payload_txt, '$.r') AS ref_page,
        json_extract_scalar(payload_txt, '$.overlayName') AS overlay_nm,
        cntxt_nm,
        json_extract_scalar(page_attr, '$.nm') AS page_nm,
        actn_catg_nm,
        actn_sub_catg_nm,
        'itemclick' AS source_type
    FROM ww_csd_dl_tables.csd_site_traffic_rptr_event_log_vw a
    JOIN invited_users i ON i.pg_cust_id = a.pg_cust_id
    WHERE event_dt BETWEEN DATE '{start_dt}' AND DATE '{end_dt}'
      AND (assoc_ind = 'false' OR assoc_ind IS NULL)
      AND actn_sub_catg_nm = 'itemClick'
),

carousel_item_clicks AS (
Select * from item_clicks where ((cntxt_nm = 'sparkyAssistant' AND page_nm = 'productPage') 
               OR (overlay_nm = 'sparkyChatWindow') )),

------------------- ADDTOCART CLICKS -------------------
atc_clicks AS (
    SELECT event_dt, 
           pg_cust_id, 
           brwsr_sessn_cooke_val,
           actn_catg_nm,
           actn_sub_catg_nm,
           cntxt_nm,
           CAST(from_unixtime(cast(event_ts_epoch AS double) / 1000) 
                AT TIME ZONE 'America/Los_Angeles' AS timestamp) AS event_ts_epoch,
           json_extract_scalar(page_attr, '$.nm') AS page_nm,
           json_extract_scalar(payload_txt, '$.r') AS ref_page,
           json_extract_scalar(payload_txt, '$.overlayName') AS overlay_nm,
           json_extract_scalar(payload_txt, '$.pageViewId') as pageViewId,
           COALESCE(json_extract_scalar(payload_txt, '$.itemDetails.itemId'),
                    json_extract_scalar(payload_txt, '$.itemId'),
                    json_extract_scalar(payload_txt, '$.itemDetails.usitemId')) AS item_id,
           MAX(json_extract_scalar(payload_txt, '$.shopId')) AS shop_id
    FROM ww_csd_dl_tables.csd_site_traffic_rptr_event_log_vw
    WHERE event_dt between DATE '{start_dt}' AND DATE '{end_dt}'
      AND (assoc_ind = 'false' OR assoc_ind IS NULL)
      AND actn_catg_nm = 'onClick'
      AND actn_sub_catg_nm IN ('addToCart','addAllToCart')
      AND json_extract_scalar(page_attr, '$.nm') != 'arPlatform'
    GROUP BY 1,2,3,4,5,6,7,8,9,10,11,12
),

dedupe AS (
    SELECT a.*, 
           ROW_NUMBER() OVER (
               PARTITION BY a.pg_cust_id, brwsr_sessn_cooke_val, actn_sub_catg_nm, item_id
               ORDER BY shop_id DESC, overlay_nm DESC, event_ts_epoch
           ) AS rn_atc,
           ROW_NUMBER() OVER (
               PARTITION BY a.pg_cust_id, brwsr_sessn_cooke_val, actn_sub_catg_nm, cntxt_nm, shop_id, item_id
               ORDER BY event_ts_epoch
           ) AS rn_aatc
    FROM atc_clicks a
    JOIN invited_users i ON i.pg_cust_id = a.pg_cust_id
),

atc AS (
    SELECT event_dt, 
           pg_cust_id, 
           brwsr_sessn_cooke_val,  
           actn_catg_nm,
           actn_sub_catg_nm,
           cntxt_nm,
           event_ts_epoch,
           page_nm,
           ref_page,
           overlay_nm,
           pageViewId,
           item_id,
           shop_id
    FROM dedupe 
    WHERE CASE WHEN actn_sub_catg_nm = 'addToCart' THEN rn_atc = 1 ELSE rn_aatc = 1 END
    AND ((cntxt_nm = 'sparkyAssistant' AND page_nm = 'productPage') OR (overlay_nm = 'sparkyChatWindow') )
),

------------------- CAROUSEL MESSAGE EVENTS -------------------
carousel AS (
    SELECT 
      CAST((from_iso8601_timestamp(event_ts) AT TIME ZONE 'America/Los_Angeles') AS date) AS event_dt_pst,
      cust_id,
      gls_app_sessn_id,
      CAST((from_iso8601_timestamp(event_ts) AT TIME ZONE 'America/Los_Angeles') AS timestamp) AS event_ts_pst,
      LEAD(CAST((from_iso8601_timestamp(event_ts) AT TIME ZONE 'America/Los_Angeles') AS timestamp))
        OVER (
          PARTITION BY 
            CAST((from_iso8601_timestamp(event_ts) AT TIME ZONE 'America/Los_Angeles') AS date),
            cust_id,
            gls_app_sessn_id
          ORDER BY 
            CAST((from_iso8601_timestamp(event_ts) AT TIME ZONE 'America/Los_Angeles') AS timestamp)
        ) AS next_event_ts_pst,
      'message' AS actn_catg_nm,
      'message' AS actn_sub_catg_nm,
      'carousel' AS cntxt_nm,
      'carousel' AS page_nm,
      'carousel' AS ref_page,
      'carousel' AS overlay_nm,
      corrltn_id AS correlation_id,
      CASE
    WHEN strpos(curr_enty_nm, 'products=') > 0
      THEN substr(curr_enty_nm, strpos(curr_enty_nm, 'products='), 200)
    ELSE NULL
  END AS product_inner,
      conversation_id AS shop_id
    FROM WW_CSD_DL_TABLES.CSD_SITE_TRFC_CNVRS_LOG a
    JOIN invited_users i ON i.pg_cust_id = a.cust_id
    WHERE CAST((from_iso8601_timestamp(event_ts) AT TIME ZONE 'America/Los_Angeles') AS date)
          BETWEEN DATE '{start_dt}' AND DATE '{end_dt}'
      AND chnl_id = 'RAPTOR_IOS_APP'
      AND curr_enty_nm LIKE '%products=%'
),

carousel_msgs AS (
    SELECT 
      event_dt_pst,
      cust_id,
      gls_app_sessn_id,
       event_ts_pst,
       next_event_ts_pst,
      actn_catg_nm,
      actn_sub_catg_nm,
      cntxt_nm,
      page_nm,
      ref_page,
      overlay_nm,
      correlation_id,    
      shop_id
    FROM carousel
    where product_inner is not null
),

------Final Combined Events-----------------
all_events AS (
    SELECT
        event_dt,
        pg_cust_id AS customer_id,
        brwsr_sessn_cooke_val AS session_id,
        event_ts,
        shop_id,
        item_id,
        pageViewId,
        ref_page,
        overlay_nm,
        cntxt_nm,
        page_nm,
        actn_catg_nm,
        actn_sub_catg_nm,
        Null as correlation_id
    FROM carousel_item_clicks

    UNION ALL

    SELECT
        event_dt,
        pg_cust_id AS customer_id,
        brwsr_sessn_cooke_val AS session_id,
        event_ts_epoch AS event_ts, -- Rename to match
        shop_id,
        item_id,
        pageViewId,
        ref_page,
        overlay_nm,
        cntxt_nm,
        page_nm,
        actn_catg_nm,
        actn_sub_catg_nm,
        Null as correlation_id
    FROM atc

    UNION ALL

    SELECT
        event_dt_pst AS event_dt,
        cust_id AS customer_id,
        gls_app_sessn_id AS session_id,
        event_ts_pst AS event_ts,
        shop_id,
        Null as item_id,
        Null as pageViewId,
        ref_page,
        overlay_nm,
        cntxt_nm,
        page_nm,
        actn_catg_nm,
        actn_sub_catg_nm,
        correlation_id
    FROM carousel_msgs
),

a as (SELECT event_dt,
      customer_id,
      session_id,
      event_ts,
      actn_catg_nm,
      actn_sub_catg_nm,
      cntxt_nm,
      page_nm,
      ref_page,
      overlay_nm,
      correlation_id,
      MAX(CASE WHEN correlation_id IS NOT NULL THEN correlation_id END)
        OVER (
            PARTITION BY customer_id, session_id, event_dt
            ORDER BY event_ts
            ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
        ) AS correlation_id_filled,
      pageViewId,
      shop_id,
      item_id
FROM all_events
ORDER BY event_dt, customer_id, session_id, event_ts)

Select 
COUNT(DISTINCT CASE WHEN actn_sub_catg_nm = 'message' THEN correlation_id_filled
    END) AS carousel_imp_reach,
COUNT(DISTINCT CASE WHEN actn_sub_catg_nm = 'itemClick' THEN correlation_id_filled
    END) AS carousel_PDPClicks_reach,
COUNT(DISTINCT CASE WHEN actn_sub_catg_nm = 'addToCart' THEN correlation_id_filled
    END) AS carousel_DirectATC_reach
From a where correlation_id_filled is not null
"""

cur.execute(sql)
rows = cur.fetchall()
cols = [desc[0] for desc in cur.description]
carousel_funnel_reach_metrics = pd.DataFrame(rows, columns=cols)
carousel_funnel_reach_metrics.head()

Carousel Funnel Impressions Reach

   carousel_imp_reach  carousel_PDPClicks_reach  carousel_DirectATC_reach
0               92621                     19571                     19994

## Cutomer Usage - Shop Engagement Volume - ATCs

In [ ]:
print("ATC Context Category Breakdown")

sql = f"""
WITH invited_users AS (
SELECT DISTINCT pg_cust_acct_id AS pg_cust_id
FROM gpadata_analytics.{invited_users}),

atc_clicks as (SELECT event_dt, 
       pg_cust_id, 
       brwsr_sessn_cooke_val,
       actn_catg_nm,
       actn_sub_catg_nm,
       cntxt_nm,
       CAST(from_unixtime(cast(event_ts_epoch as double) / 1000) AT TIME ZONE 'America/Los_Angeles' AS timestamp) AS event_ts_epoch,
       json_extract_scalar(page_attr, '$.nm') AS page_nm,
       json_extract_scalar(payload_txt, '$.r') AS referencepage,
       json_extract_scalar(payload_txt, '$.overlayName') AS overlay_nm,
       COALESCE(json_extract_scalar(payload_txt, '$.itemDetails.itemId'), 
                json_extract_scalar(payload_txt, '$.itemId'),
                json_extract_scalar(payload_txt, '$.itemDetails.usitemId')) AS item_id,
       MAX(json_extract_scalar(payload_txt, '$.shopId')) shop_id
FROM ww_csd_dl_tables.csd_site_traffic_rptr_event_log_vw
WHERE event_dt BETWEEN DATE '{start_dt}' AND DATE '{end_dt}'
AND (assoc_ind = 'false' OR assoc_ind is null) -- Exclude the associates
AND actn_catg_nm = 'onClick'
AND actn_sub_catg_nm in ('addToCart', 'addAllToCart')
AND json_extract_scalar(page_attr, '$.nm') != 'arPlatform'
GROUP BY 1,2,3,4,5,6,7,8,9,10,11),

dedupe AS (SELECT a.*, 
          row_number() OVER (PARTITION BY a.pg_cust_id, brwsr_sessn_cooke_val, actn_sub_catg_nm, item_id ORDER BY shop_id DESC, overlay_nm DESC, event_ts_epoch) AS rn_atc, -- Remove duplicates add to carts
          row_number() OVER (PARTITION BY a.pg_cust_id, brwsr_sessn_cooke_val, actn_sub_catg_nm, cntxt_nm, shop_id, item_id ORDER BY event_ts_epoch) AS rn_aatc -- Remove duplicates add all to carts
FROM atc_clicks a
JOIN invited_users i
ON i.pg_cust_id = a.pg_cust_id),

atc AS (
    SELECT
        event_dt,
        pg_cust_id,
        brwsr_sessn_cooke_val,
        actn_catg_nm,
        actn_sub_catg_nm,
        cntxt_nm,
        event_ts_epoch,
        page_nm,
        referencepage,
        overlay_nm,
        item_id,
        shop_id
    FROM dedupe
    WHERE CASE WHEN actn_sub_catg_nm = 'addToCart' THEN rn_atc = 1 ELSE rn_aatc = 1 END
)

SELECT            -- Browse Shop
    SUM(CASE WHEN cntxt_nm = 'browseShop' AND page_nm = 'browseShop' AND actn_sub_catg_nm = 'addToCart' AND COALESCE(overlay_nm,'') <> 'sparkyChatWindow' THEN 1 ELSE 0 END) AS DirectBrowseShopATC,
    SUM(CASE WHEN cntxt_nm = 'browseShop' AND page_nm = 'browseShop' AND actn_sub_catg_nm = 'addAllToCart' AND COALESCE(overlay_nm,'') <> 'sparkyChatWindow' THEN 1 ELSE 0 END) AS DirectBrowseShopAATC,
    SUM(CASE WHEN cntxt_nm = 'productPage' AND page_nm = 'productPage' AND referencepage = 'browseShop' AND actn_sub_catg_nm = 'addToCart' THEN 1 ELSE 0 END) AS PDPBrowseShopATC,
    ----Event-------------------
    SUM(CASE WHEN cntxt_nm = 'eventShop' AND page_nm = 'eventShop' AND actn_sub_catg_nm = 'addToCart' AND COALESCE(overlay_nm,'') <> 'sparkyChatWindow' THEN 1 ELSE 0 END) AS DirectEventShopATC,
    SUM(CASE WHEN cntxt_nm = 'eventShop' AND page_nm = 'eventShop' AND actn_sub_catg_nm = 'addAllToCart' AND COALESCE(overlay_nm,'') <> 'sparkyChatWindow' THEN 1 ELSE 0 END) AS DirectEventShopAATC,
    SUM(CASE WHEN cntxt_nm = 'productPage' AND page_nm = 'productPage' AND referencepage = 'eventShop' AND COALESCE(overlay_nm,'') <> 'sparkyChatWindow' AND actn_sub_catg_nm = 'addToCart' THEN 1 ELSE 0 END) AS PDPEventShopATC,
    -- Weekly Shop
    SUM(CASE WHEN cntxt_nm = 'weeklyShop' AND page_nm = 'weeklyShop' AND actn_sub_catg_nm = 'addToCart' AND COALESCE(overlay_nm,'') <> 'sparkyChatWindow' THEN 1 ELSE 0 END) AS DirectWeeklyShopATC,
    SUM(CASE WHEN cntxt_nm = 'weeklyShop' AND page_nm = 'weeklyShop' AND actn_sub_catg_nm = 'addAllToCart' AND COALESCE(overlay_nm,'') <> 'sparkyChatWindow' THEN 1 ELSE 0 END) AS DirectWeeklyShopAATC,
    SUM(CASE WHEN cntxt_nm = 'productPage' AND page_nm = 'productPage' AND referencepage = 'weeklyShop' AND actn_sub_catg_nm = 'addToCart' AND COALESCE(overlay_nm,'') <> 'sparkyChatWindow' THEN 1 ELSE 0 END) AS PDPWeeklyShopATC,
    -- Category Shop
    SUM(CASE WHEN cntxt_nm = 'categoryShop' AND page_nm = 'categoryShop' AND actn_sub_catg_nm = 'addToCart' AND COALESCE(overlay_nm,'') <> 'sparkyChatWindow' THEN 1 ELSE 0 END) AS DirectCategoryShopATC,
    SUM(CASE WHEN cntxt_nm = 'categoryShop' AND page_nm = 'categoryShop' AND actn_sub_catg_nm = 'addAllToCart' AND COALESCE(overlay_nm,'') <> 'sparkyChatWindow' THEN 1 ELSE 0 END) AS DirectCategoryShopAATC,
    SUM(CASE WHEN cntxt_nm = 'productPage' AND page_nm = 'productPage' AND referencepage = 'categoryShop' AND actn_sub_catg_nm = 'addToCart' AND COALESCE(overlay_nm,'') <> 'sparkyChatWindow' THEN 1 ELSE 0 END) AS PDPCategoryShopATC,
    -- Sparky/Carousel
    SUM(CASE WHEN ((cntxt_nm = 'sparkyAssistant' AND page_nm = 'productPage') OR (overlay_nm = 'sparkyChatWindow')) THEN 1 ELSE 0 END) AS DirectCarouselATC,
    -- Discover More
    SUM(CASE WHEN (cntxt_nm = 'shopPage' AND page_nm = 'discoverMore' AND actn_sub_catg_nm IN ('addToCart')) THEN 1 ELSE 0 END) AS DiscoverMoreATC,
    SUM(CASE WHEN cntxt_nm = 'productPage' AND page_nm = 'productPage' AND referencepage = 'discoverMore' AND actn_sub_catg_nm = 'addToCart' THEN 1 ELSE 0 END) AS PDPDiscoverMoreATC,
    -- Cart
    SUM(CASE WHEN cntxt_nm = 'cart' AND actn_sub_catg_nm = 'addToCart' AND COALESCE(overlay_nm,'') <> 'sparkyChatWindow' THEN 1 ELSE 0 END) AS DirectCartATC,
    SUM(CASE WHEN cntxt_nm = 'productPage' AND page_nm = 'productPage' AND referencepage IN ('cart') AND COALESCE(overlay_nm,'') <> 'sparkyChatWindow' AND actn_sub_catg_nm = 'addToCart' THEN 1 ELSE 0 END) AS PDPCartATC,
    -- Order Details
    SUM(CASE WHEN cntxt_nm = 'orderDetails' AND page_nm = 'orderDetails' AND actn_sub_catg_nm = 'addToCart' AND COALESCE(overlay_nm,'') <> 'sparkyChatWindow' THEN 1 ELSE 0 END) AS DirectOrderDetailsATC,
    SUM(CASE WHEN cntxt_nm = 'productPage' AND page_nm = 'productPage' AND referencepage = 'orderDetails' AND COALESCE(overlay_nm,'') <> 'sparkyChatWindow' AND actn_sub_catg_nm = 'addToCart' THEN 1 ELSE 0 END) AS PDPOrderDetailsATC,
    -- PDP from productPage
    SUM(CASE WHEN cntxt_nm = 'productPage' AND page_nm = 'productPage' AND referencepage = 'productPage' AND COALESCE(overlay_nm,'') <> 'sparkyChatWindow' AND actn_sub_catg_nm = 'addToCart' THEN 1 ELSE 0 END) AS PDPProductPageATC,
    -- Overall and Generic
    SUM(CASE WHEN cntxt_nm = 'productPage' AND page_nm = 'productPage' AND actn_sub_catg_nm = 'addToCart' THEN 1 ELSE 0 END) AS OverallProductPageATC
FROM atc
"""

cur.execute(sql)
rows = cur.fetchall()
cols = [desc[0] for desc in cur.description]
atc_context_pivot = pd.DataFrame(rows, columns=cols)
atc_context_pivot.head()
atc_context_pivot

ATC Context Category Breakdown

,DirectBrowseShopATC,DirectBrowseShopAATC,PDPBrowseShopATC,DirectEventShopATC,DirectEventShopAATC,PDPEventShopATC,DirectWeeklyShopATC,DirectWeeklyShopAATC,PDPWeeklyShopATC,DirectCategoryShopATC,...,PDPCategoryShopATC,DirectCarouselATC,DiscoverMoreATC,PDPDiscoverMoreATC,DirectCartATC,PDPCartATC,DirectOrderDetailsATC,PDPOrderDetailsATC,PDPProductPageATC,OverallProductPageATC
0,446,0,51,70,127,7,1336,754,93,3295,...,1283,24699,2483,1379,7589,445,3262,168,4767,10897

## Customer Usage - Shop Engagement Volume - Item Clicks

In [ ]:
print("Item Clicks Grouped by Context Category")

sql = f"""
WITH invited_users AS (
    SELECT DISTINCT pg_cust_acct_id AS pg_cust_id
    FROM gpadata_analytics.{invited_users}
),

item_clicks AS (
    SELECT DISTINCT
        event_dt,
        a.pg_cust_id,
        brwsr_sessn_cooke_val,
        actn_catg_nm,
        actn_sub_catg_nm,
        cntxt_nm,
        CAST(
            from_unixtime(CAST(event_ts_epoch AS double) / 1000)
            AT TIME ZONE 'America/Los_Angeles' AS timestamp
        ) AS event_ts_epoch,
        json_extract_scalar(payload_txt, '$.pageViewId') AS pageViewId,
        json_extract_scalar(page_attr, '$.nm') AS page_nm,
        json_extract_scalar(payload_txt, '$.r') AS ref_page,
        json_extract_scalar(payload_txt, '$.overlayName') AS overlay_nm,
        COALESCE(
            json_extract_scalar(payload_txt, '$.itemDetails.itemId'),
            json_extract_scalar(payload_txt, '$.itemId'),
            json_extract_scalar(payload_txt, '$.itemDetails.usitemId')
        ) AS item_id,
        json_extract_scalar(payload_txt, '$.shopId') AS shop_id
    FROM ww_csd_dl_tables.csd_site_traffic_rptr_event_log_vw a
    JOIN invited_users i ON i.pg_cust_id = a.pg_cust_id
    WHERE event_dt BETWEEN DATE '{start_dt}' AND DATE '{end_dt}'
      AND (assoc_ind = 'false' OR assoc_ind IS NULL)
      AND actn_sub_catg_nm = 'itemClick'
)

SELECT
    SUM(CASE 
        WHEN cntxt_nm = 'browseShop' AND page_nm = 'browseShop' AND overlay_nm IS NULL
        THEN 1 ELSE 0 END) AS browse_shop_itemClick,
        
    SUM(CASE 
        WHEN cntxt_nm = 'eventShop' AND page_nm = 'eventShop' AND overlay_nm IS NULL
        THEN 1 ELSE 0 END) AS event_shop_itemClick,

    SUM(CASE 
        WHEN cntxt_nm = 'weeklyShop' AND page_nm = 'weeklyShop' AND overlay_nm IS NULL
        THEN 1 ELSE 0 END) AS weekly_shop_itemClick,    
    SUM(CASE 
        WHEN cntxt_nm = 'categoryShop' AND page_nm = 'categoryShop' AND overlay_nm IS NULL
        THEN 1 ELSE 0 END) AS category_shop_itemClick,

    SUM(CASE 
        WHEN ( (cntxt_nm = 'sparkyAssistant' AND page_nm = 'productPage') 
               OR (overlay_nm = 'sparkyChatWindow') )
        THEN 1 ELSE 0 END) AS carousel_itemClick
FROM item_clicks
"""

cur.execute(sql)
rows = cur.fetchall()
cols = [desc[0] for desc in cur.description]
item_clicks = pd.DataFrame(rows, columns=cols)
item_clicks.head()

Item Clicks Grouped by Context Category

,browse_shop_itemClick,event_shop_itemClick,weekly_shop_itemClick,category_shop_itemClick,carousel_itemClick
0,523,712,3047,10524,30985

## Customer Usage - Shop Engagement Volume - Messages

In [ ]:
print("Messages grouped by Context Category")

sql = f"""
WITH invited_users AS (
    SELECT DISTINCT pg_cust_acct_id AS pg_cust_id
    FROM gpadata_analytics.{invited_users}
),

messages AS (
    SELECT  
        event_dt, 
        a.pg_cust_id, 
        cntxt_nm,
        brwsr_sessn_cooke_val,
        actn_sub_catg_nm,
        json_extract_scalar(page_attr, '$.nm') AS page_nm,
        json_extract_scalar(payload_txt, '$.pageViewId') as pageViewId
    FROM ww_csd_dl_tables.csd_site_traffic_rptr_event_log_vw a
    JOIN invited_users i
      ON i.pg_cust_id = a.pg_cust_id
    WHERE event_dt BETWEEN DATE '{start_dt}' AND DATE '{end_dt}'
      AND (assoc_ind = 'false' OR assoc_ind IS NULL)
      AND json_extract_scalar(payload_txt, '$.buttonName') = 'sendSparkyChat'
    GROUP BY 1,2,3,4,5,6,7
)

SELECT
    SUM(CASE 
        WHEN cntxt_nm = 'browseShop' AND page_nm = 'browseShop'
        THEN 1 ELSE 0 END) AS browse_shop_msg,
        
    SUM(CASE 
        WHEN cntxt_nm = 'eventShop' AND page_nm = 'eventShop'
        THEN 1 ELSE 0 END) AS event_shop_msg,

    SUM(CASE 
        WHEN cntxt_nm = 'weeklyShop' AND page_nm = 'weeklyShop'
        THEN 1 ELSE 0 END) AS weekly_shop_msg,
    SUM(CASE 
        WHEN cntxt_nm = 'categoryShop' AND page_nm = 'categoryShop'
        THEN 1 ELSE 0 END) AS category_shop_msg,

    SUM(CASE 
        WHEN cntxt_nm = 'homePage' AND page_nm = 'homePage'
        THEN 1 ELSE 0 END) AS home_page_msg,

    SUM(CASE 
        WHEN cntxt_nm = 'productPage' AND page_nm = 'productPage'
        THEN 1 ELSE 0 END) AS product_page_msg

FROM messages
"""

cur.execute(sql)
rows = cur.fetchall()
cols = [desc[0] for desc in cur.description]
messages_by_shop = pd.DataFrame(rows, columns=cols)
messages_by_shop

Messages grouped by Context Category

,browse_shop_msg,event_shop_msg,weekly_shop_msg,category_shop_msg,home_page_msg,product_page_msg
0,163,166,946,11987,60749,2366

## Business Enablement - Total Orders (Both Classic and Raptor App) by Logged In Users

In [ ]:
print("Total Order Count for Logged-In Users")

sql = f"""
WITH invited_users AS (
    SELECT DISTINCT pg_cust_acct_id AS pg_cust_id
    FROM gpadata_analytics.{invited_users}
),
login_customers AS (
    SELECT DISTINCT a.pg_cust_id AS login_users
    FROM (
        SELECT DISTINCT pg_cust_id, visitor_cooke_val, brwsr_sessn_cooke_val
        FROM ww_csd_dl_tables.csd_site_traffic_rptr_event_log_vw
        WHERE event_dt BETWEEN DATE '{start_dt}' AND DATE '{end_dt}'
          AND (assoc_ind = 'false' OR assoc_ind IS NULL)
          AND json_extract_scalar(page_attr, '$.nm') = 'homePage'
          AND actn_catg_nm = 'pageView'
    ) a
    JOIN invited_users i
      ON i.pg_cust_id = a.pg_cust_id
)
SELECT COUNT(DISTINCT order_nbr) AS total_order_count_bothApps
FROM ww_crew_dl_rpt_vm.cnsld_order_item
WHERE
    CAST(order_plcd_ts_utc AS DATE) BETWEEN DATE '{start_dt}' AND DATE '{end_dt}'
    AND order_plcd_dt BETWEEN DATE '{start_dt}' - INTERVAL '1' DAY AND DATE '{end_dt}' + INTERVAL '1' DAY
    AND op_cmpny_cd = 'WMT.COM'
    AND tenant_ste_nm IN ('US_GLASS_IPHONE', 'US_GLASS_ANDROID')
    AND cust_id IN (
        SELECT DISTINCT CAST(login_users AS VARCHAR) FROM login_customers
    )
"""

cur.execute(sql)
rows = cur.fetchall()
cols = [desc[0] for desc in cur.description]
order_count_both_apps = pd.DataFrame(rows, columns=cols)
order_count_both_apps.head()

Total Order Count for Logged-In Users

   total_order_count_bothApps
0                       51472

## Interaction Quality - Raptor CQS

In [ ]:
print("Validation Scores (Compliance, Verbosity, Truthfulness, Relevance, Coverage)")

cqs_scores = load_bq_data(f"""
    SELECT
        SUM(compliance_and_safety)/COUNT(correlation_id) AS Compliance_and_Safety,
        SUM(verbosity_and_coherence)/COUNT(correlation_id) AS Verbosity_and_Coherence,
        SUM(truthfulness_and_walmart_context)/COUNT(correlation_id) AS Truthfulness_and_Walmart_Context,
        SUM(answer_relevance)/COUNT(correlation_id) AS Answer_Relevance,
        1 - SUM(fallback_non_relevance)/COUNT(correlation_id) AS Question_Coverage
    FROM (
        SELECT
            ds,
            conversation_id,
            a.correlation_id,
            input_text,
            converse_short_reply,
            b.* EXCEPT(correlation_id),
            IF(
                (label_brand_preference IN ('compliant')
                    AND label_brand_safety IN ('safe')
                    AND label_customer_safety IN ('safe')
                    AND label_prompt_leakage IN ('compliant')
                    AND label_automation_leakage IN ('compliant')
                )
                OR label_fallback_relevance IS NOT NULL,
                1, 0
            ) AS compliance_and_safety,
            IF(
                (label_coherence IN ('coherent')
                    AND label_verbosity IN ('concise')
                )
                OR label_fallback_relevance IS NOT NULL,
                1, 0
            ) AS verbosity_and_coherence,
            IF(
                (label_evidence_entailment IN ('evident_present_or_inferred'))
                OR label_fallback_relevance IS NOT NULL,
                1, 0
            ) AS truthfulness_and_walmart_context,
            IF(
                label_response_relevance IN ('relevant')
                OR label_fallback_relevance IN ('relevant'),
                1, 0
            ) AS answer_relevance,
            IF(
                label_fallback_relevance IN ('not_relevant'),
                1, 0
            ) AS fallback_non_relevance
        FROM `wmt-et-converse-prod.converse_logs_ds_xrsamurai.logs_parsed` a
        JOIN `wmt-et-converse-prod.converse_logs_ds_xrsamurai.labelbox_validation_parsed_vw` b
            ON a.correlation_id = b.correlation_id
        WHERE
            converse_intent IN ("open_dialog", "out_of_domain_intent")
            AND ds BETWEEN '{start_dt}' AND '{end_dt}'
    )
""")

cqs_scores.head()

Validation Scores (Compliance, Verbosity, Truthfulness, Relevance, Coverage)

,Compliance_and_Safety,Verbosity_and_Coherence,Truthfulness_and_Walmart_Context,Answer_Relevance,Question_Coverage
0,1.0,0.102899,0.050473,0.884933,0.97221

## Interaction Experience - Carousel Relevance

In [ ]:
print("Carousel Relevance Score (count, average)")

carousel_scores = load_bq_data(f"""
    WITH correlation_id_sumary AS (
        SELECT 
            ds, 
            l.correlation_id, 
            COUNT(*) AS item_count, 
            COUNT(CASE WHEN carousel_item_relevance IN ('perfect_match', 'good_match', 'plausible_match', 'irrelevant') THEN 1 END) AS label_count
        FROM `wmt-et-converse-prod.converse_logs_ds_xrsamurai.labelbox_carousel_parsed_vw` l
        JOIN `wmt-et-converse-prod.converse_logs_ds_xrsamurai.logs_parsed` m 
            ON m.correlation_id = l.correlation_id
        WHERE ds BETWEEN '{start_dt}' AND '{end_dt}'
        GROUP BY 1, 2
    ),
    correlation_id_label AS (
        SELECT 
            b.ds, 
            b.correlation_id, 
            b.item_count, 
            a.item_id,
            CASE 
                WHEN carousel_item_relevance = 'perfect_match' THEN 1000
                WHEN carousel_item_relevance = 'good_match' THEN 100
                WHEN carousel_item_relevance = 'plausible_match' THEN 10
                WHEN carousel_item_relevance = 'irrelevant' THEN 1
            END AS carousel_item_relevance
        FROM `wmt-et-converse-prod.converse_logs_ds_xrsamurai.labelbox_carousel_parsed_vw` AS a
        JOIN correlation_id_sumary AS b 
            ON a.correlation_id = b.correlation_id
        WHERE b.item_count > 0
            AND b.item_count = b.label_count
    ),
    correlation_id_score AS (
        SELECT 
            ds, 
            correlation_id, 
            item_count, 
            SUM(carousel_item_relevance) / (item_count * 1000) AS carousel_item_relevance_score
        FROM correlation_id_label
        GROUP BY 1,2,3
    )
    SELECT 
        COUNT(DISTINCT correlation_id) AS num_of_carousel,
        AVG(carousel_item_relevance_score) AS relevance_score
    FROM correlation_id_score
""")

carousel_scores.head()

Carousel Relevance Score (count, average)

   num_of_carousel  relevance_score
0            29989         0.767864

## Raptor Order Id table creation

In [ ]:
sql = f"""
WITH invited_users AS (
    SELECT DISTINCT pg_cust_acct_id AS pg_cust_id
    FROM gpadata_analytics.{invited_users}
)
SELECT DISTINCT order_id AS total_order_ids
FROM (
    SELECT DISTINCT event_dt,
                    pg_cust_id, 
                    json_extract_scalar(payload_txt, '$.orderId') AS order_id
    FROM ww_csd_dl_tables.csd_site_traffic_rptr_event_log_vw
    WHERE event_dt BETWEEN DATE '{start_dt}' AND DATE '{end_dt}'
      AND (assoc_ind = 'false' OR assoc_ind IS NULL) -- Exclude the associates
      AND cntxt_nm = 'checkout'
      AND json_extract_scalar(page_attr, '$.nm') = 'thankYou'
      AND actn_catg_nm = 'pageView'
) a
JOIN invited_users i
  ON i.pg_cust_id = a.pg_cust_id
"""

# Run your SQL
cur.execute(sql)
rows = cur.fetchall()
cols = [desc[0] for desc in cur.description]
order_ids = pd.DataFrame(rows, columns=cols)

# Show result
order_ids.head()

   total_order_ids
0  200013992869438
1  200013718866887
2  200013936387312
3  200013923004703
4  200013739248666

In [ ]:
# Upload DataFrame as a table (temporary or named, e.g. 'temp_order_ids')
order_ids.to_gbq('temp.raptor_order_id', project_id='wmt-et-ccomm-prod', if_exists='replace')

## Final Table

In [ ]:
# Merge side by side
df_final = pd.concat([glass_app_session, login_users, interacted_users, bounce_users, meaningful_interacted_users, meaningful_interacted_sessn, meaningful_interected_event_counts, 
                      opened_shop_cust, opened_shop_sessn,count_opened_shop, created_shop, created_shop_type, atc_users, checkout_users,
                       order_users, repeated_order_users, inchat_bounce_users, final_agent_summary, inchat_msg, session_duration, latency_percentiles, users_w_carousel_imp, pdp_imp, shop_engagement_reach_metrics, 
                       carousel_funnel_reach_metrics, atc_context_pivot, item_clicks, messages_by_shop, order_count_both_apps, cqs_scores, carousel_scores], axis=1)

df_final

,classic_users,classic_sessn,login_users,login_sessn,interacted_users,interacted_sessn,bounce_cust_ct,bounce_sessn_ct,users_meaningful_interaction,users_sent_msg,...,weekly_shop_itemClick,category_shop_itemClick,carousel_itemClick,browse_shop_msg,event_shop_msg,weekly_shop_msg,category_shop_msg,home_page_msg,product_page_msg,total_order_count_bothApps
0,7943,534438,8428,92605,8412,85815,243,260,8053,7663,...,3047,10524,30985,163,166,946,11987,60749,2366,51472

In [ ]:
# Run this cell and paste the values of the table in excel file directly
df_final.to_clipboard(index=True)